window.createDEC15Reader=function({getState,save,esc,lesson,sources,toast}){
  let selection=null,wordCard=null,game=null;const drafts={};
  const st=()=>getState();const marks=id=>(st().marks||{})[id]||[];
  function raw(id){return id.startsWith('n-')?String(st().values[id.slice(2)]||''):(drafts[id]?.text??st().markDocuments?.[id]?.text??'')}
  function renderText(id,text){const ranges=marks(id).filter(r=>r.end<=text.length),points=[...new Set([0,text.length,...ranges.flatMap(r=>[r.start,r.end])])].sort((a,b)=>a-b);return points.slice(0,-1).map((start,i)=>{const end=points[i+1],active=ranges.filter(r=>r.start<=start&&r.end>=end),colour=active.filter(r=>r.type!=='underline').at(-1)?.type,under=active.some(r=>r.type==='underline');const content=esc(text.slice(start,end));return colour||under?`<span class="annotation ${colour?'mark-'+colour:''}${under?' mark-underline':''}">${content}</span>`:content}).join('')}
  function text(id,value,title){drafts[id]={text:value,title};return `<span class="markable-text" data-mark-text="${id}">${renderText(id,value)}</span>`}
  function toolbar(scope){return `<div class="mark-tools" data-mark-scope="${scope}" role="group" aria-label="Text marking tools"><span class="tool-caption">Select text →</span><button type="button" data-mark-action="yellow" title="Highlight selected text in yellow"><i class="swatch yellow" aria-hidden="true"></i>Highlight</button><button type="button" data-mark-action="blue" title="Highlight selected text in blue"><i class="swatch blue" aria-hidden="true"></i>Blue</button><button type="button" data-mark-action="underline"><span class="underline-icon" aria-hidden="true">U</span>Underline</button><button type="button" data-mark-action="erase">Remove marks</button></div>`}
  function noteField(id,label,placeholder,rows){const key='n-'+id;return `<div class="note-field" data-note-field="${key}"><label class="field-label" for="field-${id}">${esc(label)}</label><div class="note-topline"><div class="note-tabs" role="group" aria-label="View for ${esc(label)}"><button type="button" data-note-view="write" data-note-id="${key}" aria-pressed="true">Write</button><button type="button" data-note-view="mark" data-note-id="${key}" aria-pressed="false">See my marks</button></div><span class="note-save-hint">Saved on this device</span></div>${toolbar(key)}<textarea id="field-${id}" data-save="${id}" data-mark-note="${key}" rows="${rows}" placeholder="${esc(placeholder)}">${esc(raw(key))}</textarea><div class="note-marked" data-note-preview="${key}" hidden tabindex="0" aria-label="Marked version of ${esc(label)}">${text(key,raw(key),label)||''}</div></div>`}
  function remember(){const focused=document.activeElement;if(focused?.matches('textarea[data-mark-note]')){if(focused.selectionEnd>focused.selectionStart)selection={id:focused.dataset.markNote,start:focused.selectionStart,end:focused.selectionEnd,value:focused.value};return}const sel=window.getSelection();if(!sel||sel.isCollapsed||!sel.rangeCount)return;const r=sel.getRangeAt(0),el=(r.startContainer.nodeType===1?r.startContainer:r.startContainer.parentElement)?.closest('[data-mark-text]');if(!el||!el.contains(r.endContainer)){selection=null;return;}const pre=r.cloneRange();pre.selectNodeContents(el);pre.setEnd(r.startContainer,r.startOffset);const start=pre.toString().length;selection={id:el.dataset.markText,start,end:start+r.toString().length,value:raw(el.dataset.markText)}}
  function noteView(id,view){const box=document.querySelector(`[data-note-field="${id}"]`);if(!box)return;box.querySelector('textarea').hidden=view==='mark';const preview=box.querySelector('[data-note-preview]');preview.hidden=view!=='mark';preview.innerHTML=text(id,raw(id),box.querySelector('.field-label').textContent);box.querySelectorAll('[data-note-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.noteView===view));if(view==='mark'&&!raw(id).trim())preview.innerHTML='<p class="empty-note">Write a note first. Then select words to highlight or underline.</p>'}
  function apply(type,scope){remember();if(!selection||!(scope==='reading'?selection.id.startsWith('s-'):scope==='activity'?/^(q-|c-)/.test(selection.id):scope===selection.id)){toast('Select words within one paragraph or one note in this area first.');return}const {id,start,end,value}=selection;if(value!==raw(id)||end<=start){toast('The text changed. Select the words again.');selection=null;return}st().marks??={};let list=marks(id);if(type==='erase'){list=list.flatMap(r=>r.end<=start||r.start>=end?[r]:[{...r,end:Math.min(r.end,start)},{...r,start:Math.max(r.start,end)}].filter(x=>x.end>x.start))}else list=[...list,{start,end,type}];st().marks[id]=list;st().markDocuments??={};st().markDocuments[id]=drafts[id]||st().markDocuments[id];save();if(id.startsWith('n-'))noteView(id,'mark');else document.querySelectorAll('[data-mark-text]').forEach(el=>{if(el.dataset.markText===id){el.innerHTML=renderText(id,raw(id));decorate(el)}});toast(type==='erase'?'Marks removed from the selected words.':'Your text marks are saved.');}
  function noteChanged(id,oldText,newText){const key='n-'+id;if(oldText===newText)return;let a=0,b=0;while(a<oldText.length&&a<newText.length&&oldText[a]===newText[a])a++;while(b<oldText.length-a&&b<newText.length-a&&oldText[oldText.length-1-b]===newText[newText.length-1-b])b++;const oldEnd=oldText.length-b,delta=newText.length-oldText.length;if(st().marks?.[key])st().marks[key]=marks(key).flatMap(r=>r.end<=a?[r]:r.start>=oldEnd?[{...r,start:r.start+delta,end:r.end+delta}]:[]);if(selection?.id===key)selection=null}
  function closeWord(){wordCard?.remove();wordCard=null;document.querySelectorAll('[data-word][aria-expanded=true]').forEach(x=>x.setAttribute('aria-expanded','false'))}
  function showWord(target){const item=lesson.glossary.find(x=>x[0]===target.dataset.word);if(!item)return;closeWord();target.setAttribute('aria-expanded','true');wordCard=document.createElement('aside');wordCard.className='word-sticky';wordCard.setAttribute('role','dialog');wordCard.setAttribute('aria-label','Word meaning: '+item[0]);wordCard.innerHTML=`<button data-close-word aria-label="Close word meaning">×</button><span class="sticky-kicker">IN PLAIN WORDS</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p><div class="word-example">${esc(item[2])}</div>`;(document.querySelector('dialog[open]')||document.body).appendChild(wordCard);const r=target.getBoundingClientRect(),w=Math.min(320,innerWidth-24);wordCard.style.width=w+'px';wordCard.style.left=Math.max(12,Math.min(r.left,innerWidth-w-12))+'px';wordCard.style.top=Math.max(12,Math.min(r.bottom+9,innerHeight-wordCard.offsetHeight-14))+'px';wordCard.querySelector('button').focus({preventScroll:true});wordCard.wordTrigger=target}
  const termMap=new Map(lesson.glossary.map(x=>[x[0].toLowerCase(),x[0]]));const pattern=new RegExp('\\b('+[...termMap.keys()].sort((a,b)=>b.length-a.length).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\b','gi');
  function decorate(root,seen=null){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('button,textarea,select,[data-word],.note-marked,.word-sticky,.glossary-word,.game-board,.source-tabs,.mark-tools')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const txt=node.textContent;pattern.lastIndex=0;if(!pattern.test(txt))continue;let changed=false;pattern.lastIndex=0;let pos=0,frag=document.createDocumentFragment();for(const m of txt.matchAll(pattern)){const term=termMap.get(m[0].toLowerCase());if(seen){if(seen.has(term))continue;seen.add(term)}frag.append(txt.slice(pos,m.index));const el=document.createElement('span');el.className='word-help';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',m[0]+': show meaning');el.setAttribute('aria-expanded','false');el.dataset.word=term;el.textContent=m[0];frag.append(el);pos=m.index+m[0].length}frag.append(txt.slice(pos));if(pos)node.replaceWith(frag)}}
  function mount(){closeWord();const seen=new Set();document.querySelectorAll('[data-help]').forEach(el=>decorate(el,seen))}
  function markedRecords(){return Object.entries(st().marks||{}).filter(([,rs])=>rs.length).map(([id,rs])=>({id,rs,value:raw(id),title:id.startsWith('n-')?drafts[id]?.title||st().markDocuments?.[id]?.title||id.slice(2):(drafts[id]?.title||st().markDocuments?.[id]?.title||id)}))}
  function notebookMarks(){const records=markedRecords();return `<section class="notebook-entry marked-notebook"><span class="content-tag">YOUR SAVED TEXT MARKS</span><h3>Highlighted &amp; underlined</h3><p class="field-hint">Yellow and blue = your highlights. A line below = your underline. Marks show your choices, not checked answers.</p>${records.length?records.map(r=>`<div class="saved-mark"><h4>${esc(r.title)}</h4><p>${renderText(r.id,r.value)}</p></div>`).join(''):'<p>Select words in a reading, a task question, or your notes. Then use Highlight or Underline.</p>'}</section>`}
  function exportLines(){return markedRecords().flatMap(r=>[r.title,...r.rs.map(m=>'['+m.type+'] '+r.value.slice(m.start,m.end)),''])}
  function exportHtml(entries){const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My DEC15 notes and text marks</title><style>body{max-width:900px;margin:45px auto;padding:0 25px;color:#172a38;font:17px/1.8 system-ui}h1,h2{line-height:1.3}section{border-top:1px solid #ccc;padding:20px 0}.mark-yellow{background:#ffe496}.mark-blue{background:#cdeafa}.mark-underline{text-decoration:underline;text-decoration-thickness:2px;text-underline-offset:3px}p{white-space:pre-wrap;overflow-wrap:anywhere}h4{margin-bottom:5px}</style><h1>My DEC15 notes</h1><p>Week ${lesson.week}, Day ${lesson.day} · ${esc(lesson.question)}</p>${entries.map(({a,entries:es})=>`<section><h2>${esc(a.title)}</h2>${es.map(([k,v])=>`<h4>${esc(k)}</h4><p>${esc(v)}</p>`).join('')}</section>`).join('')}${notebookMarks()}</html>`;download(html,`DEC15-W${lesson.week}D${lesson.day}-marked-notebook.html`,'text/html;charset=utf-8')}
  function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your marked notebook has been downloaded.')}
  function openGame(){const words=['claim','evidence','assumption','bias','limitation','paraphrase'].map(w=>lesson.glossary.find(x=>x[0]===w));game={words,order:[3,0,5,1,4,2],done:[],word:null,message:'Choose a word on the left. Then choose its meaning on the right.'};paintGame();document.querySelector('#resource-dialog').showModal()}
  function paintGame(){document.querySelector('#resource-title').textContent='Word pairs';document.querySelector('#resource-body').innerHTML=`<section class="word-game"><span class="studio-kicker">OPTIONAL · PLAY ALONE OR WITH A PARTNER</span><h3>Six words. Six meanings.</h3><p>Choose a word, then its meaning. If they do not match, try again. There is no time limit.</p><div class="game-meter"><span>${game.done.length} / 6 pairs found</span><progress max="6" value="${game.done.length}" aria-label="Word pairs found"></progress></div><div class="game-board"><div aria-label="Words">${game.words.map((x,i)=>`<button data-game-word="${i}" aria-pressed="${game.word===i}"${game.done.includes(i)?' disabled':''}>${esc(x[0])}${game.done.includes(i)?' ✓':''}</button>`).join('')}</div><div aria-label="Meanings">${game.order.map(i=>`<button data-game-meaning="${i}"${game.done.includes(i)?' disabled':''}>${esc(game.words[i][1].split('. ')[0])}${game.done.includes(i)?' ✓':''}</button>`).join('')}</div></div><p class="game-message" role="status">${esc(game.message)}</p>${game.done.length===6?'<div class="game-finish">All six matched! Choose one word and give your partner a new example.</div><button data-word-game>Play again ↻</button>':''}</section>`}
  document.addEventListener('selectionchange',remember);document.addEventListener('select',remember,true);document.addEventListener('mouseup',remember);document.addEventListener('keyup',remember);
  document.addEventListener('mousedown',e=>{if(e.target.closest('[data-mark-action]')){remember();e.preventDefault()}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&wordCard){e.preventDefault();e.stopPropagation();const target=wordCard.wordTrigger;closeWord();target?.focus()}if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-word]')){e.preventDefault();showWord(e.target)}},true);
  document.addEventListener('click',e=>{const t=e.target.closest('[data-mark-action],[data-note-view],[data-word],[data-close-word],[data-word-game],[data-game-word],[data-game-meaning]');if(!t)return;if(t.dataset.markAction)apply(t.dataset.markAction,t.closest('[data-mark-scope]').dataset.markScope);if(t.dataset.noteView)noteView(t.dataset.noteId,t.dataset.noteView);if(t.dataset.word&&!(e.detail>0&&window.getSelection()?.toString()))showWord(t);if(t.hasAttribute('data-close-word')){const trigger=wordCard?.wordTrigger;closeWord();trigger?.focus()}if(t.hasAttribute('data-word-game'))openGame();if(t.hasAttribute('data-game-word')){game.word=Number(t.dataset.gameWord);game.message='Now choose the meaning of “'+game.words[game.word][0]+'”.';paintGame();document.querySelector(`[data-game-word="${game.word}"]`)?.focus()}if(t.hasAttribute('data-game-meaning')){const i=Number(t.dataset.gameMeaning);if(game.word===null)game.message='Choose a word on the left first.';else if(game.word===i){game.done.push(i);game.message='Matched: '+game.words[i][0]+'. '+game.words[i][2];game.word=null}else game.message='Not a match yet. Keep your word and try another meaning.';paintGame();document.querySelector('[data-game-word]:not(:disabled)')?.focus()}});
  function markRecords(){return markedRecords().map(r=>({title:r.title,html:renderText(r.id,r.value),ranges:[...r.rs].sort((x,y)=>x.start-y.start).map(m=>({type:m.type,text:r.value.slice(m.start,m.end)}))}))}
  return {noteField,text,toolbar,mount,decorate,noteChanged,notebookMarks,markRecords,exportLines,exportHtml,closeWord};
};
