/* Classroom interactions share the existing local notebook. No accounts or network calls. */
window.createDEC15Studio = function ({val, set, esc, lesson, toast}) {
  const labels = {'a1-focus':'My practice focus','b2-round':'Taking turns: round','b2-observed':'A behaviour my partner noticed','b3-obstacle':'A situation to work on','c2-ranking':'Evidence investigation order','d4-round':'Explaining evidence: round','d6-keepsake':'A piece of work to keep'};
  const focusOptions=['Explain one connection','Ask a useful question','Build on someone’s idea'];
  const obstacles=[
    ['I have an idea but cannot start speaking.','Before the next discussion, prepare one sentence opening. Practise saying it quietly with a partner.','Count whether you used the opening once.'],
    ['I lose track while someone is speaking.','During discussion, write two keywords. Use them to ask a checking question.','Ask your partner whether your paraphrase matched their idea.'],
    ['I collect facts but cannot explain them.','After choosing evidence, say why it matters for the question. Ask a partner to identify the connection.','Keep one evidence note with your own explanation.'],
    ['I notice the same language error again.','After a task, record one original phrase, its correction and a new sentence.','Use the corrected pattern in one new sentence and check it.']
  ];
  const roleNames=['Idea maker','Question asker','Connection finder'];
  const roleLines=['Explain one reason: “Food waste may matter because…”','Ask for the reason or evidence. “What makes you say that?”','Connect to a previous point. “Building on that idea…”'];
  const challengeLines=['How does that answer “How critical”?','What has to be true for that connection to work?','Does the source support the place, people and time in your claim?'];
  function shell(id,kicker,title,copy,body){return `<section class="studio-panel" data-studio="${id}" aria-label="${esc(title)}"><div class="studio-heading"><span class="studio-kicker">${kicker}</span><h3>${title}</h3><p>${copy}</p></div>${body}</section>`}
  function choice(key,items){return `<div class="choice-grid" role="group" aria-label="${esc(labels[key])}">${items.map((x,i)=>`<button type="button" class="choice-card" data-studio-choice="${key}" data-choice-index="${i}" aria-pressed="${val(key)===x}"><span class="choice-index" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><span>${esc(x)}</span><span class="choice-tick" aria-hidden="true">${val(key)===x?'✓':'+'}</span></button>`).join('')}</div>`}
  function rank(){return String(val('c2-ranking')).split(' > ').filter(x=>['A','B','C'].includes(x))}
  function ranking(){const order=rank(),a=lesson.sections.flatMap(s=>s.activities).find(a=>a.id==='c2');return shell('c2','PAIR CHALLENGE · WITHIN YOUR 10 MINUTES','Be an evidence detective','First choose your own order. Then compare with a partner. Which statement gives you details that you could check?',`<div class="rank-track" aria-live="polite">${[0,1,2].map(i=>`<div><span>${i===0?'Easiest to check':i===1?'Next':'Hardest to check'}</span><strong>${order[i]||'?'}</strong></div>`).join('')}</div><p class="studio-instruction">${order.length<3?`Choose your ${['first','second','third'][order.length]} card below.`:'Your order is saved. Explain your reasoning below before opening the feedback.'}</p><div class="detective-cards">${a.cases.map((t,i)=>{const letter='ABC'[i],n=order.indexOf(letter);return `<div class="detective-card"><span class="evidence-letter" aria-hidden="true">${letter}</span><p>${esc(t.slice(3))}</p><button data-rank="${letter}"${n>=0?' disabled':''} aria-label="${n>=0?`Card ${letter} ranked ${n+1}`:`Choose card ${letter} next`}">${n>=0?`Ranked ${n+1}`:'Choose next'}${n>=0?' ✓':' →'}</button></div>`}).join('')}</div><button class="text-button" data-rank-reset>Reset ranking</button><p class="studio-footnote">Having details to check does not mean a statement is true. If two cards seem equally easy to check, choose an order and explain the tie. Your partner may choose a different order. Ask why.</p>`)}
  function relay(id){const isReason=id==='d4',round=Number(val(id+'-round'))||1;if(isReason)return shell(id,'PAIR CHALLENGE · 2 ROUNDS','Explain why it matters','A: read one of your evidence notes and explain why it supports your answer. B: read the question on the dark card. A: answer it and improve your explanation. Then change speakers.',`<div class="relay-challenge"><span>ROUND ${round} / 2</span><strong>${round===1?'A explains · B asks':'B explains · A asks'}</strong><p>“${challengeLines[Number(val('d4-card'))||0]}”</p></div><div class="studio-buttons"><button data-challenge>Try another question ↻</button><button data-relay="d4">${round===1?'Swap speakers →':'Return to round 1'}</button></div><p class="studio-footnote">Write both improved explanations below. Working alone? Say the explanation, then ask yourself the question.</p>`);
    const offset=round-1;return shell('b2','TAKE TURNS · 4 MINUTES','Explain. Ask. Add an idea.','Call yourselves A, B and C. Think quietly for 20 seconds. Read your job card, then speak in the order A → B → C. After about a minute, click Change speaking jobs.',`<div class="role-deck">${['A','B','C'].map((seat,i)=>{const n=(i+offset)%3;return `<div class="role-card"><span>SEAT ${seat}</span><h4>${roleNames[n]}</h4><p>${roleLines[n]}</p></div>`}).join('')}</div><div class="studio-buttons"><span class="round-label">Round ${round} / 3</span><button data-relay="b2">${round<3?'Change speaking jobs →':'Return to round 1'}</button></div><details class="studio-help"><summary>Working in a pair or on your own?</summary><p>With two people: A gives a reason; B asks a question and adds an idea. Then change jobs. Alone: write one reason, a question about it, and one related idea.</p></details><p class="studio-instruction">After taking turns, choose one action your partner saw or heard. Ask them to repeat the words you used.</p>${choice('b2-observed',['I gave a reason','I asked a question','I linked to another idea'])}<p class="studio-footnote">Write the actual example below. You may practise a keyword in a language you know, then say your idea in English.</p>`)}
  function obstacle(){const chosen=val('b3-obstacle'),row=obstacles.find(o=>o[0]===chosen);return shell('b3','CHOOSE · TRY · ADAPT','Start with a real moment','Choose a moment you have experienced, or write your own example below. Then try one action that could help.',`${choice('b3-obstacle',obstacles.map(o=>o[0]))}${row?`<div class="strategy-reveal" role="status"><span class="content-tag">A strategy to try</span><p>${esc(row[1])}</p><span class="content-tag">Something you can observe</span><p>${esc(row[2])}</p><p class="studio-footnote">Adapt this to your group. Say who will do what, and when.</p></div>`:'<div class="strategy-empty">Select a situation to explore one practical action.</div>'}`)}
  function questStatus(){const entries=[];for(let i=0;i<200;i++){if(val('d3-note-'+i)&&val('d3-source-'+i))entries.push({note:String(val('d3-note-'+i)).trim(),source:val('d3-source-'+i),link:String(val('d3-link-'+i)).trim()})}const names=['Tchonkouang et al. (2023)','Royer (2024)','Our Changing Climate (2020)'];return `<div class="quest-grid">${names.map((s,i)=>{const found=entries.some(e=>e.source===s&&e.note.length>=12);return `<div class="quest-item${found?' collected':''}"><span aria-hidden="true">${found?'✓':'○'}</span><strong>${['Reading 1','Reading 2','Listening'][i]}</strong><small>${found?'A note is recorded':'Add a source + note'}</small></div>`}).join('')}</div><p class="quest-status">${entries.filter(e=>e.note.length>=12&&e.link.length>=8).length} note(s) include a source and an explanation. This checks presence, not accuracy.</p>`}
  function receipt(){const options=['An improved connection','A source limitation I can explain','My essay position'];const selected=val('d6-keepsake')||options[0],saved=selected===options[0]?val('d4-f0'):selected===options[1]?val('c5-f1'):val('d5-thesis');return shell('d6','SEE WHAT YOU LEARNED','Before / now / next','Compare one early idea with a piece of work from later today. Name a specific change; it is also useful to notice what is still unclear.',`<div class="receipt-start"><span class="content-tag">Before · your opening note</span><blockquote>${esc(val('a1-f0')||'No opening note saved. Use your paper notes or say what you first thought.')}</blockquote></div>${choice('d6-keepsake',options)}<div class="receipt-now"><span class="content-tag">Now · your own work</span><blockquote>${esc(saved||'No note saved here yet. Choose another piece of work, or write your example below.')}</blockquote></div><p class="studio-footnote">Your chosen focus: <strong>${esc(val('a1-focus')||'Not selected')}</strong>. What can you point to in your work? Download notes keeps your choices and written responses.</p>`)}
  function render(id){switch(id){case 'a1':return shell('a1','YOUR CHOICE TODAY','Choose something to practise','Pick one action to try today. You can change your choice. At the end, look for an example in your own work.',choice('a1-focus',focusOptions)+'<p class="studio-footnote">Start quietly, then share with one partner. You can read from your notes.</p>');case 'b2':case 'd4':return relay(id);case 'b3':return obstacle();case 'c2':return ranking();case 'd3':return shell('d3','WORK TOGETHER · WITHIN YOUR 25 MINUTES','Collect. Connect. Check.','In a group of three, start with a different source each. In a pair, take one reading each and share the listening. Bring your notes together and group them by main idea.',`<div data-quest-status aria-live="polite">${questStatus()}</div><details class="studio-help"><summary>Check a partner’s note</summary><p>Ask your partner to find the original paragraph. Check that the note keeps the same meaning in new words. Ask why the note matters for the essay. Keep the place and time attached to each figure. Filled boxes alone do not show that evidence is accurate or useful.</p></details>`);case 'd6':return receipt();default:return ''}}
  function refresh(id){const el=document.querySelector(`[data-studio="${id}"]`);if(!el)return;el.outerHTML=render(id)}
  function handle(t){if(t.dataset.studioChoice){const key=t.dataset.studioChoice,opts=key==='a1-focus'?focusOptions:key==='b3-obstacle'?obstacles.map(o=>o[0]):key==='b2-observed'?['I gave a reason','I asked a question','I linked to another idea']:['An improved connection','A source limitation I can explain','My essay position'];set(key,opts[Number(t.dataset.choiceIndex)]);refresh(key.split('-')[0]);document.querySelector(`[data-studio-choice="${key}"][data-choice-index="${t.dataset.choiceIndex}"]`)?.focus({preventScroll:true});return true}if(t.dataset.rank){const order=rank();if(!order.includes(t.dataset.rank)){order.push(t.dataset.rank);set('c2-ranking',order.join(' > '));refresh('c2');const next=document.querySelector('[data-rank]:not(:disabled)')||document.querySelector('[data-rank-reset]');next?.focus({preventScroll:true});toast(order.length===3?'Order saved. Explain your reasoning before checking guidance.':`Card ${t.dataset.rank} ranked ${order.length}. Choose the next card.`)}return true}if(t.hasAttribute('data-rank-reset')){set('c2-ranking','');refresh('c2');document.querySelector('[data-rank]')?.focus({preventScroll:true});return true}if(t.dataset.relay){const id=t.dataset.relay,max=id==='b2'?3:2;set(id+'-round',((Number(val(id+'-round'))||1)%max)+1);refresh(id);toast(`Round ${val(id+'-round')}: jobs changed. Read your new speaking job.`);document.querySelector(`[data-relay="${id}"]`)?.focus({preventScroll:true});return true}if(t.hasAttribute('data-challenge')){set('d4-card',((Number(val('d4-card'))||0)+1)%3);refresh('d4');document.querySelector('[data-challenge]')?.focus({preventScroll:true});return true}return false}
  function update(){const el=document.querySelector('[data-quest-status]');if(el){const html=questStatus();if(el.innerHTML!==html)el.innerHTML=html}}
  return {render,refresh,handle,update,labels,rank};
};
