/* DEC15 · Week 5 — protected course texts (copied exactly from the Teacher's Book; do not edit).
   Headings inside a text start with "## ". Added to any texts already loaded (a day can load Week 3 + Week 5). */
window.DEC15_SOURCES = (window.DEC15_SOURCES || []).filter(s => !["clapp", "oxfam", "mockshell"].includes(s.id)).concat([
  {
    "id": "clapp",
    "short": "Reading · Clapp et al.",
    "title": "The case for a six-dimensional food security framework",
    "cite": "Clapp et al. (2022)",
    "kind": "Core reading",
    "reference": "Adapted from: Clapp, J., Moseley, W. G., Burlingame, B., & Termine, P. (2022). Viewpoint: The case for a six-dimensional food security framework. Food Policy, 106, Article 102164. https://doi.org/10.1016/j.foodpol.2021.102164",
    "citeAs": "Cite as Clapp et al. (2022) or (Clapp et al., 2022).",
    "paragraphs": [
      "A. Over the last 50 years, our understanding of food security has grown to include four main areas: availability, access, utilization, and stability (FAO, 2006; Webb et al., 2006; CFS, 2009; Upton et al., 2016). However, the growing inequalities in food systems and the deeper understanding of how closely linked our ecological and food systems are, point to the need for two more dimensions: agency and sustainability. Agency and sustainability are becoming increasingly important as we recognize the need for food systems that are not only productive but also equitable and environmentally sustainable. Including these dimensions in the food security framework would help address broader issues such as empowerment of communities and long-term resource management.",
      "## The Four-Pillars of Food Security",
      "B. The pillar of availability focuses on the actual presence of food in a specific location. This aspect deals with the supply side of food security, ensuring there is enough food through local production, imports, or aid. It includes the total food production, stock levels, and the ability to deliver food to markets (United Nations, 1975). Availability must be stable to prevent shortages that can lead to hunger and malnutrition (Upton et al., 2016). Factors such as farming practices, weather conditions, and political stability play a significant role in influencing food production and distribution.",
      "C. Access involves ensuring that individuals can obtain healthy foods. This pillar is not only about physical availability but also about sufficient economic resources to obtain food. Key factors that affect access include household income, food prices, and the distribution of food within the market. Access is critical because the physical presence of food does not necessarily mean people can obtain it (Sen, 1981). Thus, policies aimed at improving food access often focus on improving economic opportunities, reducing inequality, and ensuring that people have enough resources to buy healthy food.",
      "D. Utilization refers to the body’s ability to obtain nutrients from food. This pillar emphasizes the quality of food. Proper utilization ensures that consumption leads to nutritional well-being. Factors affecting utilization include food safety, food quality, dietary diversity, and individuals’ health status, which can influence how effectively nutrients are absorbed and used by the body. Utilization is often conceptualized as being dependent on availability and access (Webb et al., 2006; Upton et al., 2016). That is, food must be both available and accessible before nutritional benefits can be gained.",
      "E. Stability addresses the need for the other three pillars to be consistent over time. It ensures that food security is constant and reliable. Stability helps to prevent sudden food shortages caused by unexpected events like climatic events, political unrest, economic changes, or other crises (FAO, 1982). Stability means that availability, access, and utilization are not periodically interrupted but are reliable and predictable year-round. This pillar is crucial, especially in regions prone to conflicts, natural disasters, or economic crises, which can cause periodic food shortages or disruptions in access (FAO, 2006).",
      "## Agency and Sustainability",
      "F. Despite advancements in understanding food security, significant challenges remain. According to the FAO et al. (2021), nearly one in three people globally faced food insecurity in 2020. This situation calls for a re-evaluation of the traditional four-pillar framework of food security to include agency and sustainability. These additional areas provide a better understanding of the growing complexities of food insecurity. They also encourage a more holistic approach to solving these issues.",
      "G. Agency in food security means the ability of individuals and groups to make decisions that influence their lives, including their nutritional status and food security. It is about having the power to shape food-related decisions and actions that affect one’s community and personal well-being (Sen, 1985). The concept of agency is crucial for resolving inequalities within food systems. It ensures that all community members, especially the marginalized, can participate in decision-making processes that affect their food security. For instance, the 2021 Food Systems Summit highlighted the role of agency in achieving fair and sustainable food systems. The Summit noted that addressing power imbalances and building agency are essential for reducing poverty and enhancing food security.",
      "H. Agency is particularly important in addressing the needs of vulnerable groups, including women, small-scale farmers, and indigenous communities. Enhancing agency involves ensuring these groups have the knowledge, resources, and power to make decisions about food production, distribution, and consumption. It also means they can actively participate in shaping policies and practices that affect their food security and overall well-being.",
      "I. Sustainability in food security means sustaining food production going for a long time without depleting or harming natural resources. It involves using methods that help the earth’s resources renew themselves, making sure future generations can also have enough food (HLPE, 2020). As the world faces challenges like climate change, loss of biodiversity, and environmental damage, focussing on sustainable practices is increasingly important (Ingram, 2011; Ericksen, 2008). These practices are crucial not only to avoid using up resources but also to make sure food systems can withstand unexpected changes and challenges.",
      "J. In conclusion, effectively resolving food insecurity requires the inclusion of both agency and sustainability in the existing framework of food security. By doing this, food security policies can address immediate food needs, empower individuals and communities and protect the environment. This approach will help create a more comprehensive strategy for long-term food security, ultimately leading to more resilient food systems and healthier communities."
    ],
    "figure": "assets/week5/six-pillars.svg",
    "figureAlt": "The six dimensions of food security: availability, access, utilisation, stability, and the two new dimensions agency and sustainability.",
    "figureCaption": "Six dimensions of food security.",
    "figureCredit": "Based on Clapp et al. (2022) and HLPE (2020)."
  },
  {
    "id": "oxfam",
    "short": "Listening · Oxfam",
    "title": "How much money would it take to end world hunger?",
    "cite": "Oxfam (2022)",
    "kind": "Core listening transcript",
    "reference": "Adapted from: Oxfam. (2022). How much money would it take to end world hunger? https://www.oxfamamerica.org/explore/stories/how-much-money-would-it-take-to-end-world-hunger/",
    "citeAs": "Cite as Oxfam (2022) or (Oxfam, 2022).",
    "note": "Listen first; then read to check.",
    "paragraphs": [
      "When tech entrepreneur Elon Musk challenged the United Nations last year to show him a $6 billion plan that would end world hunger, he got in return a proposal that would save 42 million people in 43 countries from starvation.",
      "Since Musk’s challenge, the hunger crisis has worsened—increasing the number of people in need and driving up costs. Extreme hunger has more than doubled in the world’s worst climate hotspots, and about 1 in 10 people worldwide suffer from chronic hunger—meaning they do not consume enough food to maintain a normal, active lifestyle.",
      "At Oxfam, we’ve been focused on food and hunger since our founding. So, we’re going to explain what money could accomplish, step by step: How close are we to Zero Hunger; how much money could help achieve it; and what money can’t solve, including what else we must do if we are serious about ending world hunger.",
      "Let’s begin by examining how close we are to ending world hunger.",
      "Seven years after world leaders committed to end hunger by 2030, the crisis is heading in the wrong direction. The UN reports that 150 million more people are affected by hunger since the start of the global pandemic. That means as many as 828 million people experienced hunger in 2021—more than three times the size of the US population.",
      "There are two main dimensions of the crisis. Some people suffer from extreme hunger—meaning their lack of adequate food puts their lives and livelihoods at risk. Many fled their homes due to conflict, the effects of climate change, and lost income as a result of economic lockdowns during the pandemic. Others suffer from chronic hunger. This includes mostly women farmers that work small plots of land. Many lack access to finance as well as other support to improve their farming practices and are now increasingly unable to grow enough food because of extreme weather events.",
      "In the words of Mohanna Ahmed Ali Eljabaly from the Yemen Family Care Association, “It is abysmal that with all the technology in agriculture and harvesting techniques today we are still talking about famine in the 21st century. This is not about one country or one continent, and hunger never only has one cause. This is about the injustice of the whole of humanity.”",
      "So, how much money could help end world hunger? Current estimates suggest that we need donor governments to invest around $37 billion every year until 2030 to tackle both extreme and chronic hunger.",
      "Let’s start with extreme hunger. We need about $23 billion just this year to meet the needs of people facing starvation and acute malnutrition. These resources—primarily for cash and food assistance—represent almost half of what is needed to meet the world’s overall humanitarian needs. But world leaders never fully fund what is needed every year. In 2021, they contributed only 46 percent toward the total cost of global humanitarian needs.",
      "Given all this, how much more money would it take to address chronic hunger? According to Ceres2030, an initiative led by foundations, universities, and scientists working to find solutions to hunger, donor governments would need to invest an additional $14 billion on average in foreign aid every year until 2030 to end hunger sustainably. That means roughly doubling the amount of foreign aid from wealthy governments for food security and nutrition each year. That additional investment is equal to about 1 percent of what the world spends annually on military and arms projects.",
      "Low- and middle-income countries also have a role to play. According to Ceres, these governments would need to raise revenue to spend on average around $19 billion every year until 2030 toward ending hunger.",
      "However, not all efforts needed to end hunger revolve around money. There is more that must be done. To end world hunger, we need to recognize why people are hungry at a time when we have enough food globally to feed 10 billion people. No amount of money can end war, stop the effects of the climate crisis on food production, or take away the power that giant corporations have over agricultural trade—all of which make ending hunger that much harder.  In fact, the food system itself is a driver of the climate crisis—responsible for almost 1/3 of total carbon emissions.",
      "That’s why we need to transform our food systems if we’re serious about ending world hunger. That starts with supporting local food production and thriving local food systems while pushing giant corporations that dominate global food markets to do right by people and the planet.",
      "Food entrepreneurs from Asia to Latin America have their own vision to grow healthy food in their local communities. Women and youth need tools to help grow, process, and distribute food in a fair and sustainable manner.",
      "Large global food and beverage companies wield incredible power over the livelihoods of women, workers, and farmers who sustain their operations. They must provide equal pay and treatment for women, mitigate the effects of the climate crisis on food production, and move away from business models that prioritize short-term profit over human and planetary well-being.",
      "Smallholder farmers produce 1/3 of the world’s food but are struggling to adapt to the climate crisis. Many are adopting climate-resilient agriculture practices, increasing their productivity, and organizing as a collective to take advantage of market opportunities to improve their incomes.",
      "More than 50 percent of the world’s smallholder farmers are women. We need to secure their rights to land, raise their voice in decision-making spaces on the land issues that affect them, and strengthen leadership for women’s land rights.",
      "As a consumer, your choices can make the difference. Every time you sit down to a meal or go shopping for food, you have the chance to help build thriving local food systems—one critical piece to achieving Zero Hunger. That’s why Oxfam started the Eat for Good initiative to help people like you shop and eat more sustainably. Become familiar with Oxfam’s Eat for Good principle—save food, shop seasonal, eat less meat, support farmers and farm producers, and cook smart.",
      "In conclusion, ending world hunger is the best investment money can buy. By making clear financial commitments to address extreme and chronic hunger, world leaders can bring us closer to Zero Hunger in the years and decades ahead. But money is only part of the equation—and we need to transform food systems to ensure food security for all."
    ]
  },
  {
    "id": "mockshell",
    "short": "Mediation · Mockshell & Ritter",
    "title": "Applying the six-dimensional food security framework",
    "cite": "Mockshell & Ritter (2024)",
    "kind": "Mediation reading",
    "reference": "Adapted from: Mockshell, J., & Ritter, T. N. (2024). Applying the six-dimensional food security framework to examine a fresh fruit and vegetable program implemented by self-help groups during the COVID-19 lockdown in India. World Development, 175, Article 106486. https://doi.org/10.1016/j.worlddev.2023.106486",
    "citeAs": "Cite as Mockshell and Ritter (2024) or (Mockshell & Ritter, 2024).",
    "paragraphs": [
      "A. Our intended conceptual contribution is to apply Clapp et al.’s (2022) six-dimensional food security framework to examine the effects of a program aimed at improving food security during a shock. The program in question was a Fresh Fruit and Vegetable (FFV) procurement program implemented by Self Help Groups (SHGs) in India. Clapp et al.’s (2022) six-dimensional food security framework is an expansion of the traditional four dimensions of food security, namely food availability, access, utilization, and stability (FAO, 2006), to also include agency and sustainability. Agency is the ability of people to exercise control over their lives and is integral to empowerment (Clapp et al., 2022). Empowerment can generate collective action to reduce social inequalities and secure more equitable access to markets (Eyben et al., 2008). Sustainability refers to the ability of food systems to provide food and nutrition security in the present, without compromising the ability to generate food and nutrition security in the future (HLPE, 2020). We emphasize and integrate the concept of resilience in food systems into the dimension of sustainability, rather than it being another dimension (Zollet et al., 2021).",
      "## The program",
      "B. The procurement program was implemented by self-help groups (SHGs) in the Indian state of Odisha during the COVID-19 lockdown. SHGs are typically comprised of about 10 to 15 women that meet regularly and participate in saving, farming, marketing, and lending activities (Garikipati, 2008;  Kumar et al., 2021). The program allowed SHGs to purchase fresh fruits and vegetables (FFV) from producers and sell them to consumers when other supply chain participants were prohibited from operating. SHGs have been used as a platform to deliver a variety of development programs related to health, nutrition, agriculture, and empowerment (Gugerty et al., 2018, Nichols, 2021). SHG membership has been found to lead to a number of beneficial outcomes related to food security, such as food expenditures (Raghunathan et al., 2022), nutritional outcomes (Kumar et al., 2018), and women’s empowerment (Kumar et al., 2021).  The Government of Odisha has relied on SHGs in the past after natural disasters, such as cyclones, floods, and droughts, by utilizing them to distribute aid (Christian et al., 2019, Patel et al., 2020).",
      "## Effects on the six dimensions of food security",
      "## Availability and Access",
      "C. Given that FFV were largely unavailable before the program began, the program greatly increased availability. Consumers in rural and urban areas benefited from the program because it led to a continuous supply of FFV when informal and traditional markets were banned. The program positively affected food availability since it allowed sufficient quantities of high quality FFV to be sold daily to consumers. As for access, when asked to describe the major successes of the program, almost one-third of the respondents said that it increased access to nutritious foods. This was achieved through a number of mechanisms. First, participating value chain actors were able to earn income through the program at a time when other means to earn income were very limited.  Second, the program enabled consumers to have daily access to vegetables at a reasonable price. Third, very poor consumers were given free FFV, which increased access for the most vulnerable households.",
      "## Utilization and stability",
      "D. Although utilization was not frequently discussed, some respondents spoke of having to eat rotten vegetables before the program, whereas they were able to access clean and fresh vegetables through the program. Since the program was able to provide a constant supply of FFV to consumers, it stabilized FFV prices and quantities, contributing to stability. In remote areas, the program enabled consumers to buy FFV that had previously been unavailable, such as staple vegetables (potatoes and onions) grown out-of-state, due to the lockdown’s travel restrictions. Urban consumers were also able to access FFV through the program that had previously been unavailable due to travel restrictions blocking FFV from entering urban areas.",
      "## Agency",
      "E. Results show that the program’s effects on agency were mixed.  SHG members observed that the program increased collective action and a feeling of group solidarity among its members due to the time spent together coordinating the program. The program strengthened solidarity within SHGs as they supported their communities by buying from poor producers, donating to needy consumers, and bridging gaps in the supply chain. However, we also uncovered some gendered effects of the program. Women were prevented from playing a more active role in the transport and retailing of FFV, due to social norms. Women producers were discouraged from leaving the village, due to reasons such as that it would encourage gossip, that women would not be able to handle the high outdoor temperatures, and that women needed to care for young children. In addition, women were regarded as having less bargaining power than men. Men feared that women wouldn’t be able to manage customers, handle money, and that they would get cheated by customers.  Also, the program negatively impacted independent retailers not involved in it. These retailers, selling fresh fruits and vegetables (FFV) illegally during lockdown, were forced to lower prices or travel further to compete with the program, increasing their risk of fines or imprisonment. They felt neglected and resentful towards the government and the program.",
      "## Sustainability",
      "F. As described in our conceptual framework, the sustainability dimension of food security includes the concept of resilience in food systems. We integrated and emphasized the concept of resilience in food systems in the sustainability dimension, rather than focusing on sustainable agricultural practices and reduced food loss as in Clapp et al. (2022). Nevertheless, we uncovered a few ways in which the program improved sustainable agriculture. Nearly two-thirds of participating value chain actors reported that the program reduced FFV waste. In addition, SHG members credited their receiving a solar-powered cold storage facility for FFV after the program ended as a result of their improved political ties from the program.",
      "## Conclusion",
      "G. This study contributed to the literature by applying Clapp et al.’s (2022) six-dimensional food security framework to examine the effects of a specific policy (Clapp et al., 2022). The policy in question was a FFV procurement program implemented by SHGs. Through semi-structured interviews and focus group discussions, we found that the policy was able to contribute to all six dimensions of food security, albeit with mixed results on agency and sustainability. We showed that including the two additional dimensions of food security, namely agency and sustainability, allowed for a more thorough, complete, and holistic analysis of the impacts of the policy. Examining policies and programs through the lens of the six-dimensional food security framework is one step towards designing and implementing policies that are more inclusive. A multifaceted approach will help ensure that the most vulnerable are not left behind."
    ]
  }
]);
