window.DEC15_LESSON = {
  "id": "w2d5",
  "title": "From evidence to argument",
  "question": "How critical is addressing food waste as a strategy to combat global food insecurity?",
  "sections": [
    {
      "id": "ai",
      "number": "01",
      "title": "Choose how you learn",
      "subtitle": "Use AI thoughtfully",
      "minutes": 45,
      "tag": "16A · AI decisions",
      "outcome": "Decide when AI helps you practise and when it does the thinking for you.",
      "activities": [
        {
          "id": "a1",
          "title": "Remember yesterday’s lesson",
          "minutes": 8,
          "mode": "Work alone → pair",
          "intro": "First work alone. Then talk to one person beside you.",
          "steps": [
            "Choose one action to practise today. In the first box, write a reason food is wasted, a result of that waste, and one question. Try without looking at your notes.",
            "Tell your partner how food waste could affect people’s access to food. Listen to their idea. In the second box, write one idea you changed or made clearer.",
            "If you missed the last lesson, click Open Reading 1. Read paragraphs B–F for 2 minutes. Close the reading, then complete the same boxes."
          ],
          "fields": [
            {
              "label": "My cause, effect and question",
              "placeholder": "Cause: … Effect: … Question: …",
              "rows": 3
            },
            {
              "label": "One idea I revised after talking",
              "placeholder": "I first thought… After talking, I changed/clarified…",
              "rows": 3
            }
          ],
          "sources": [
            "reading1"
          ],
          "support": "Food is wasted when ___. This can lead to ___. One thing I need to understand is ___.",
          "feedback": "Check your connection against Reading 1: causes include overbuying, label confusion and production losses; effects include wasted resources and lower producer income. Keep “food loss” during production distinct from consumer “food waste”. Your question can remain open.",
          "deliverable": "Three short notes and one change after talking."
        },
        {
          "id": "a2",
          "title": "Does AI help me practise?",
          "minutes": 12,
          "mode": "Work in pairs",
          "intro": "AI means artificial intelligence. An AI chatbot can answer questions or produce writing. Read these imaginary examples; you do not need to open an AI app.",
          "steps": [
            "Read each of the six examples. Choose whether the student still practises the skill, lets AI do the skill instead, or needs to check the teacher’s rules.",
            "Compare your choices with your partner. Choose one example where you disagree. Each person explains: “The student still has to…”",
            "Click Check my decisions. Read the explanations. Write which choice you discussed and what you now think."
          ],
          "fields": [
            {
              "label": "Our most interesting disagreement",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "kind": "classify",
          "options": [
            "Supports practice",
            "Replaces the target skill",
            "Check task rules first"
          ],
          "items": [
            {
              "text": "Outside assessment, I write a sentence myself, ask a tool for another practice example, and explain the difference.",
              "answer": "Supports practice",
              "why": "You attempt the skill, compare examples and explain your reasoning. Check the output rather than assuming it is accurate."
            },
            {
              "text": "In today’s planning workshop, I ask AI to choose my position and produce my essay plan.",
              "answer": "Replaces the target skill",
              "why": "The workshop develops your ability to choose evidence and organise an argument. A ready-made plan removes that practice."
            },
            {
              "text": "I want AI to rewrite paragraphs for an assessed submission, but I have not checked the task instructions.",
              "answer": "Check task rules first",
              "why": "Check the unit outline and assessment instructions, including acknowledgement requirements. Permission and learning value are separate questions."
            },
            {
              "text": "Outside assessment, I request a short vocabulary quiz, answer from memory and check definitions in a dictionary.",
              "answer": "Supports practice",
              "why": "Retrieval and verification remain your responsibility. Use words you can later explain and use independently."
            },
            {
              "text": "I read a summary generated by AI instead of examining the sources I must evaluate in today’s workshop.",
              "answer": "Replaces the target skill",
              "why": "Evaluating sources requires reading their actual claims, evidence and limitations."
            },
            {
              "text": "A supervised test is starting and I am unsure whether a particular AI tool is permitted.",
              "answer": "Check task rules first",
              "why": "Secure assessments generally prohibit AI unless expressly permitted. Ask before using the tool; do not assume permission."
            }
          ],
          "deliverable": "Six choices and a short explanation of one disagreement."
        },
        {
          "id": "a3",
          "title": "Ask three questions before using AI",
          "minutes": 15,
          "mode": "Groups of 3",
          "intro": "Work in a group of three. Use the three questions and the imaginary situations below. No AI account is needed.",
          "steps": [
            "Choose one of the three situations below. Ask: Is it allowed? What must I learn to do myself? What information must I check?",
            "Person A explains a decision. Person B asks “What will the student still do themselves?” Person C suggests one improvement. Change jobs and discuss another situation.",
            "Write about one situation in the three boxes. If you used Cogniti or Copilot yesterday, you may add something it helped with and something it could not do well."
          ],
          "fields": [
            {
              "label": "Scenario and decision",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "What I will do myself",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "What information I would check / what AI help I would report",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "visual": "decision",
          "cases": [
            "A student asks an AI chatbot to explain the word “redistribution”. The student will then practise using the word in their own sentence.",
            "A student asks an AI chatbot to write a reflection saying what the student learned in yesterday’s group discussion.",
            "A student asks an AI chatbot to make a reference for an article that the student knows does not exist."
          ],
          "support": "It may help with ___, but I still need to ___. I would check ___ before using it.",
          "feedback": "Vocabulary explanation can support practice if you verify and use it yourself. Personal reflection needs your own experience and judgment. Inventing a reference is not acceptable. For assessment, check permission and acknowledgement requirements independently of these learning decisions.",
          "deliverable": "One decision, what you will do yourself, and what you will check."
        },
        {
          "id": "a4",
          "title": "Make a rule for your own learning",
          "minutes": 10,
          "mode": "Work alone → pair",
          "intro": "Write one action that keeps you doing the thinking in today’s lesson. Then practise answering the exact situation below.",
          "steps": [
            "In the first box, write one action and why it helps you learn. Example of the format: “I will try a new sentence myself before looking at an example.”",
            "Partner A reads the situation card aloud. Partner B says what they would do next and why. You do not need to invent a new situation or use an AI app.",
            "Change speakers. In the second box, each person writes their own answer. Then look back at Activity 3: would you change any decision?"
          ],
          "fields": [
            {
              "label": "My learning rule",
              "placeholder": "When… I will… so that I practise…",
              "rows": 3
            },
            {
              "label": "What I would do in the AI situation, and why",
              "placeholder": "First I would… because…",
              "rows": 3
            }
          ],
          "feedback": "A useful rule names an action and its purpose: “I will choose and group source evidence myself so I can explain my argument on Monday.” If a tool supplies an argument, do not substitute it for today’s independent thinking. Acknowledgement does not by itself make every use permitted.",
          "policy": true,
          "deliverable": "One learning rule and your response to the situation card.",
          "scenario": {
            "title": "Read this exact situation to your partner",
            "text": "You are planning today’s food-waste essay. You need to choose your own answer and two reasons. You open an AI chatbot. It says: “I can write your answer, both reasons, and the full paragraph for you in 10 seconds.”",
            "ask": "Partner A: “What would you do next? What thinking would you still do yourself?” Partner B: “I would… because…” Then change speakers."
          }
        }
      ]
    },
    {
      "id": "feedback",
      "number": "02",
      "title": "Turn feedback into action",
      "subtitle": "Reconnect with yesterday",
      "minutes": 45,
      "tag": "17A · Feedback literacy",
      "outcome": "Use comments about your work to choose one useful action and set clear group goals.",
      "activities": [
        {
          "id": "b1",
          "title": "Find one useful thing in your feedback",
          "minutes": 5,
          "mode": "Work alone",
          "intro": "Feedback means comments about your work. Use yesterday’s teacher or partner comments if you have them.",
          "steps": [
            "Read yesterday’s comments and your own reflection. Choose one comment about something you did well.",
            "In the first box, name the action and a real example. In the second box, write a comment you do not understand or a moment you found difficult.",
            "If you have no comments, use your memory: What did you say or do? When did you get stuck? You will get fresh comments in Activity 2."
          ],
          "fields": [
            {
              "label": "A strength, with an example",
              "placeholder": "During… I did/said… This helped because…",
              "rows": 3
            },
            {
              "label": "A question or difficulty",
              "placeholder": "At the moment when… I was unsure about…",
              "rows": 3
            }
          ],
          "feedback": "Use observable evidence, such as inviting a quiet member in, referring to a source, or asking a follow-up question. “Good discussion” is too broad to guide your next attempt.",
          "deliverable": "One real example and one question or difficulty."
        },
        {
          "id": "b2",
          "title": "Take turns: explain, ask, connect",
          "minutes": 10,
          "mode": "Discussion groups",
          "intro": "Use yesterday’s group if possible. Each person will try all three speaking jobs.",
          "steps": [
            "For 2 minutes, read Reading 1, paragraphs B–F. Write a few keywords, then close the reading.",
            "For 4 minutes, discuss: “Why can food waste matter for food insecurity?” Follow the three job cards. Click Change speaking jobs after each round.",
            "For 2 minutes, tell a partner one useful thing they said, one thing they could add, and one question. Choose the action you noticed and write the actual example below.",
            "For the last 2 minutes, compare today’s comments with yesterday’s, if available. Write one action to try next time."
          ],
          "fields": [
            {
              "label": "One observation from a peer",
              "placeholder": "My partner noticed that I said/did…",
              "rows": 3
            },
            {
              "label": "One change I will try next time",
              "placeholder": "In the next discussion I will… I will check by…",
              "rows": 3
            }
          ],
          "sources": [
            "reading1"
          ],
          "support": "I agree with ___ because ___. The source adds ___. Could you explain ___? We have not heard from ___ yet.",
          "feedback": "Check the quality of your participation: did you connect your point to evidence, respond to another person, or help someone contribute? This short replay provides new practice evidence; it does not replace yesterday’s official task feedback.",
          "deliverable": "One partner observation and one action to try."
        },
        {
          "id": "b3",
          "title": "Choose a problem. Try a helpful action.",
          "minutes": 15,
          "mode": "Discussion groups",
          "intro": "Think of a particular moment in a task. You do not need to describe your personality.",
          "steps": [
            "Choose one situation in the menu, or write a different one. Read the suggested action. Decide if it would help your group.",
            "Use 6 minutes to fill the three boxes: the problem, who will do what and when, and what you will look for to see if it helped. Practise the action briefly.",
            "For 5 minutes, talk to another group. Explain your plan and ask for one suggestion.",
            "Use the remaining time to improve the plan. Example of the format: “Before our next discussion, each person will prepare one question. Afterwards, we will check whether we asked it.”"
          ],
          "fields": [
            {
              "label": "Our stage and obstacle",
              "placeholder": "Before/during/after… we find it difficult to…",
              "rows": 3
            },
            {
              "label": "Our strategy: who does what, and when?",
              "placeholder": "When… [person] will…",
              "rows": 3
            },
            {
              "label": "How we will check whether it helped",
              "placeholder": "We will look for/count/compare…",
              "rows": 3
            }
          ],
          "feedback": "A workable strategy specifies a behaviour and a check. For example: before discussion, prepare two evidence notes; during discussion, mark each time you link a point to a source; afterwards, check whether both were used. An error log should include the original phrase, a correction and a new example.",
          "deliverable": "A small plan you can try and check."
        },
        {
          "id": "b4",
          "title": "Set three clear group goals",
          "minutes": 10,
          "mode": "Original research groups",
          "intro": "A goal says what you want to do. Make each goal small enough to see or check.",
          "steps": [
            "Open your group’s reflection form if you have it. Read the problems you expected and the actions you planned.",
            "Take turns sharing one comment you received. Discuss one change that could help your group.",
            "Write 3–5 goals for Weeks 3–4. For each, say what you will do, when, and how you will check. Example of the format: “At our next meeting, I will ask one question about the source. My partner will note the question.” Copy the goals into your course form when available."
          ],
          "fields": [
            {
              "label": "Goal 1: action + occasion + evidence",
              "placeholder": "In the next… I will… Evidence will be…",
              "rows": 3
            },
            {
              "label": "Goal 2: action + occasion + evidence",
              "placeholder": "In the next… I will… Evidence will be…",
              "rows": 3
            },
            {
              "label": "Goal 3: action + occasion + evidence",
              "placeholder": "In the next… I will… Evidence will be…",
              "rows": 3
            },
            {
              "label": "Optional goals 4–5",
              "placeholder": "In the next… I will… Evidence will be…",
              "rows": 3
            }
          ],
          "support": "In our next ___, I will ___ at least ___ times. I will check this by ___.",
          "feedback": "Goals should be specific enough to observe. “Improve speaking” needs a behaviour such as asking one follow-up question or explaining a source connection. Include an action for each area you marked as needing work.",
          "deliverable": "At least three goals: action + time + a way to check."
        },
        {
          "id": "b5",
          "title": "Check that your goal is clear",
          "minutes": 5,
          "mode": "Work alone → pair",
          "intro": "Work with a partner. Find out whether they understand your planned action.",
          "steps": [
            "Read one goal aloud. Do not show your writing. Your partner says the goal again in their own words.",
            "Compare their explanation with what you meant. If they cannot say what you will actually do, make the goal more specific.",
            "Write your improved goal below. Choose one you can try in the next reading discussion."
          ],
          "fields": [
            {
              "label": "The goal I will practise next",
              "placeholder": "When… I will… My partner can check by…",
              "rows": 3
            }
          ],
          "feedback": "You are ready to move on when your partner can describe the action, the occasion and what evidence will show it happened. Saving a goal is a first step; later performance is the evidence of improvement.",
          "deliverable": "One clear goal to try next."
        }
      ]
    },
    {
      "id": "critical",
      "number": "03",
      "title": "Question the evidence",
      "subtitle": "Read with a purpose",
      "minutes": 60,
      "tag": "18A · Criticality",
      "outcome": "Check claims, notice assumptions and missing points of view, and explain the limits of a source.",
      "activities": [
        {
          "id": "c1",
          "title": "Is it a fact I can check, or a judgement?",
          "minutes": 8,
          "mode": "Work alone → pair",
          "intro": "A factual claim can be checked against evidence. A judgement gives a view about value, importance, or what may happen. Being checkable does not make a claim true.",
          "steps": [
            "Read each statement and choose a category.",
            "Select the words that helped you choose. Use the Underline button above the statements, or underline them on paper.",
            "Choose one factual claim. In the box below, write what information you would need to check it. Then compare your decisions with the guidance."
          ],
          "fields": [
            {
              "label": "What would I need to verify one factual claim?",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "kind": "classify",
          "options": [
            "Checkable factual claim",
            "Judgment or prediction"
          ],
          "items": [
            {
              "text": "A study reported that a food-rescue programme delivered 500 meals in one week.",
              "answer": "Checkable factual claim",
              "why": "The report, count and period could be checked. This is a fictional practice claim, not established research evidence."
            },
            {
              "text": "Food-rescue programmes are the best way to solve food insecurity.",
              "answer": "Judgment or prediction",
              "why": "“Best” needs a comparison and criteria. The claim evaluates rather than only reports."
            },
            {
              "text": "Smart fridges will solve the food-waste problem.",
              "answer": "Judgment or prediction",
              "why": "“Will solve” predicts a broad outcome. A useful technology does not guarantee that outcome."
            },
            {
              "text": "The adapted Royer reading discusses food waste in the United States.",
              "answer": "Checkable factual claim",
              "why": "You can verify the geographical focus by examining the reading."
            }
          ],
          "caption": "The 500-meal example is fictional and is for reasoning practice only.",
          "deliverable": "Four choices, underlined clues, and one checking question."
        },
        {
          "id": "c2",
          "title": "Which claim is easier to check?",
          "minutes": 10,
          "mode": "Work in pairs",
          "intro": "These three claims are invented for practice. Look for details that you could investigate; do not assume a claim is true.",
          "steps": [
            "For 2 minutes, read cards A, B and C. Click Choose next on the card with the most details you could check. Choose a second card, then a third.",
            "For 3 minutes, compare your order with a partner. Say which details helped you decide. Click Reset ranking if you want to change the order.",
            "For 3 minutes, ask who made the claim, when, and how they found the information. Write your reason and one question you would check.",
            "For 2 minutes, click Compare with guidance. Read it and improve your reason if needed."
          ],
          "fields": [
            {
              "label": "My ranking and reason",
              "placeholder": "I ranked the cards… because… My partner questioned…",
              "rows": 3
            },
            {
              "label": "A question I would investigate",
              "placeholder": "Before using this claim, I would check…",
              "rows": 3
            }
          ],
          "cases": [
            "A. “Everyone knows that food-sharing apps solve hunger.”",
            "B. “A survey of 40 users of one app found that 28 reported wasting less food after four weeks. The method and questionnaire are available.”",
            "C. “An impressive study proves that food-sharing apps always eliminate household waste.”"
          ],
          "support": "This is more traceable because ___. However, it only tells us about ___. We still need to check ___.",
          "feedback": "B provides a sample, period and method to examine, but self-report, a small sample and selection effects limit the conclusion. It does not establish that the app caused the change or solved hunger. A relies on generalisation; C uses certainty without traceable details. Specificity supports investigation, not automatic trust.",
          "deliverable": "An order for the three cards, your reason, and a checking question."
        },
        {
          "id": "c3",
          "title": "Find the idea that has not been proved",
          "minutes": 12,
          "mode": "Groups of 3",
          "intro": "An assumption is an idea a writer depends on but has not shown to be true. Read the example, then try two different claims.",
          "steps": [
            "Read the phone-reminder example below. Then choose two food-waste claims from the cards.",
            "For each claim, write three things: what it assumes, a situation where it might not work, and a more careful version of the claim.",
            "In your group, one person explains, one asks “When might this not work?”, and one writes a short note. Change jobs for the second claim. Each person keeps their own final notes."
          ],
          "fields": [
            {
              "label": "Claim 1: assumption + possible exception + qualified version",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 4
            },
            {
              "label": "Claim 2: assumption + possible exception + qualified version",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 4
            }
          ],
          "example": "Worked example: “Put a reminder on your phone and you will never forget homework.” This assumes you will notice and act on every reminder. A more careful claim: “A reminder may help if you check it and allow time to act.”",
          "cases": [
            "“If supermarkets sell food at a discount before expiration, customers will always buy it instead of wasting it.”",
            "“If the government mandates food waste reduction strategies in schools, children will develop lifelong habits of responsible consumption.”",
            "“Businesses that charge customers for food waste will significantly reduce waste levels.”"
          ],
          "support": "This assumes that ___. That may not hold when ___. A more careful claim would be ___.",
          "feedback": "Discounts: price is not the only factor; storage, preferences and meal plans matter. School lessons: learning does not guarantee lasting habits; family and context influence behaviour. Fees: responses may depend on affordability, enforcement and alternatives. Do not assume the claim says more than it actually says; explain the missing link.",
          "deliverable": "Two sets of notes: assumption + exception + careful claim."
        },
        {
          "id": "c4",
          "title": "Whose point of view is missing?",
          "minutes": 15,
          "mode": "Work in pairs → group",
          "intro": "Read the paragraph below. Find the writer’s view and think about people whose experiences are not fully included.",
          "steps": [
            "Read once. In your own words, say what the writer thinks about government action.",
            "Highlight two expressions that show the writer’s view. Ask: Whose needs are discussed? Whose needs are not explained?",
            "Write one missing point of view and explain why it could matter to the argument.",
            "Compare with another pair. A writer’s strong opinion does not automatically make a claim false. Write one fair question you would ask the writer."
          ],
          "fields": [
            {
              "label": "Main position and two language clues",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "A missing perspective and why it matters",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "One fair question for the writer",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "quote": "The government is taking significant steps to address the growing problem of food waste through new policies and initiatives. Regulations requiring supermarkets and restaurants to donate surplus food instead of discarding it will help reduce unnecessary waste and support struggling families. Tax incentives for businesses that participate in food redistribution programs further encourage responsible practices. While some critics argue that these policies place an unfair burden on businesses, it is the government’s responsibility to ensure a sustainable and equitable food system. By enforcing stricter regulations and increasing public awareness, food waste can be drastically reduced, benefiting both the economy and the environment.",
          "feedback": "The paragraph supports government intervention. Phrases such as “significant steps” and “drastically reduced” reinforce that stance. It briefly mentions critics but does not develop compliance costs, practical business constraints or recipients’ experiences. These gaps suggest questions to investigate; they do not by themselves disprove the policy.",
          "deliverable": "Two language clues, one missing point of view, and one question."
        },
        {
          "id": "c5",
          "title": "Try the questions on a course reading",
          "minutes": 10,
          "mode": "Work alone → pair",
          "intro": "Use Reading 1 or Reading 2. Find something useful and something the reading cannot tell you.",
          "steps": [
            "Click a reading button. Choose one useful claim. Highlight it and record the reading title and paragraph letter.",
            "Ask: Which people, places, or years does this evidence cover? What can it not tell us about food insecurity worldwide? Write a limit and why it matters.",
            "Compare with a partner who chose the other reading. Keep the useful claim for your essay notes."
          ],
          "fields": [
            {
              "label": "Useful claim + source + paragraph",
              "placeholder": "Source… Paragraph… The claim is…",
              "rows": 3
            },
            {
              "label": "Limitation and effect on how I use the claim",
              "placeholder": "Its scope is… This limits…",
              "rows": 3
            }
          ],
          "sources": [
            "reading1",
            "reading2"
          ],
          "support": "This source is useful for ___ because ___. However, its focus on ___ means it does not establish ___.",
          "feedback": "Royer focuses on the US, so avoid automatically generalising its statistics to the world. Tchonkouang brings together international examples and reported estimates, but figures refer to different places and years. A source can be useful and limited at the same time.",
          "deliverable": "One source note and one limit you can explain."
        },
        {
          "id": "c6",
          "title": "Try a new example on your own",
          "minutes": 5,
          "mode": "Work alone",
          "intro": "Practice situation: A campus café says it had fewer leftovers after using smaller plates. A poster says: “Smaller plates will end food insecurity everywhere.”",
          "steps": [
            "Work alone. Identify the café statement you could check and the poster statement that goes too far.",
            "Write one piece of information you would need. Then rewrite the poster statement so it does not claim more than the evidence shows.",
            "After writing, click Compare with guidance. Use it to check your reasoning."
          ],
          "fields": [
            {
              "label": "My analysis and revised conclusion",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 5
            }
          ],
          "feedback": "Separate the café’s reported change from the global conclusion. Ask about quantities, time period, other changes and whether leftovers reached people in need. “Smaller plates may reduce leftovers in this café” fits the scope more closely; the report does not establish an effect on global food insecurity.",
          "deliverable": "Your own analysis and a more careful statement."
        }
      ]
    },
    {
      "id": "writing",
      "number": "04",
      "title": "Build an argument that holds",
      "subtitle": "Prepare for Monday",
      "minutes": 90,
      "tag": "19A · Writing workshop",
      "outcome": "Understand the essay question, collect evidence, choose your answer, and make your own plan.",
      "activities": [
        {
          "id": "d1",
          "title": "What is the essay asking you to do?",
          "minutes": 10,
          "mode": "Work alone → pair",
          "intro": "Read the exact essay question below. Today you make notes and a plan. You write the essay in the next workshop.",
          "steps": [
            "Select and highlight the topic words in the question. Underline the words that tell you what you must do.",
            "Explain to your partner how judging the importance of food-waste action is different from only describing food waste. Write the task and its limits below.",
            "Write your first answer to the question in one sentence. This is a starting view; you may change it after checking the sources."
          ],
          "fields": [
            {
              "label": "The topic and limits",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "What I must do beyond describing",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "My first position: my answer to the question",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "question": true,
          "feedback": "The topic is food waste and global food insecurity. “How critical” asks you to judge the importance of addressing food waste, explain causal relationships and support your position with sources. Keep the focus on this week’s input. You do not need a survey of every cause of food insecurity.",
          "deliverable": "A clear understanding of the question and a first position."
        },
        {
          "id": "d2",
          "title": "Listen, take notes, compare",
          "minutes": 20,
          "mode": "Work alone → pair",
          "intro": "Watch the video here and take notes on paper. Open “Read the video script” to check its words and times. If your teacher uses the adapted course recording instead, choose “Adapted course transcript”.",
          "steps": [
            "Before listening, write two kinds of information you expect to need for the essay, such as a cause or an effect.",
            "Watch the food-waste section from 00:00:09 to 00:09:05, or listen to the version your teacher chooses. Write keywords, numbers and links on paper. Do not try to write every sentence.",
            "Compare your notes with a partner. Put a question mark beside any number or idea you are unsure about.",
            "Listen again where needed. Open the script for the version you heard and check your notes. Type your strongest notes below. Keep video timestamps or course paragraph letters with your notes so you can find the information again."
          ],
          "fields": [
            {
              "label": "Before listening: two predictions",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            },
            {
              "label": "My selected handwritten notes, now typed",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 5
            },
            {
              "label": "One uncertainty I checked",
              "placeholder": "Write short notes here. Use the steps on the left.",
              "rows": 3
            }
          ],
          "kind": "listening",
          "support": "Use abbreviations: waste; GHG = greenhouse gases; prod. = production; approx. = approximately. Keep each statistic with its place and source.",
          "feedback": "In the supplied video script, roughly 8% refers to global emissions (00:01:05); 33.7% refers to unharvested produce in the reported California study (00:03:19); and 69% refers to household, restaurant and food-service waste as a share of annual US food waste (00:05:19). The adapted transcript has these in B, E and G. These percentages measure different things and cannot be added together.",
          "deliverable": "Handwritten notes, selected typed notes, and one checked detail."
        },
        {
          "id": "d3",
          "title": "Collect evidence for your essay",
          "minutes": 25,
          "mode": "Work in pairs or groups of 3",
          "intro": "Bring together notes from both readings and the listening. Group them by idea, such as environmental effects or access to food.",
          "steps": [
            "Use 3 minutes to choose useful groups of ideas. Write each group’s name in the Theme column.",
            "Use 14 minutes to find evidence. Divide the sources between group members. Explain each idea in your own words and record its source and paragraph. Everyone needs notes from all three sources.",
            "Use 5 minutes to compare related ideas. Do the sources agree, add information, or describe different places or groups? Explain how each note helps answer the essay question.",
            "Use 3 minutes to check your notes against the original paragraphs. Remove any note you cannot connect to the question."
          ],
          "fields": [],
          "kind": "evidence",
          "sources": [
            "reading1",
            "reading2",
            "listening"
          ],
          "support": "Both sources suggest ___. Source A explains ___, while Source B adds ___. This matters for food insecurity because ___.",
          "feedback": "Useful thematic links include wasted production resources and emissions (Reading 1 F; Reading 2 F; Listening B/D), and redistribution or food availability (Reading 1 D/G; Reading 2 E; Listening B). Keep your own selection and explain its relevance. Avoid treating hypothetical quantities of food as proof that distribution barriers have disappeared.",
          "deliverable": "An evidence table with all three sources and your explanations."
        },
        {
          "id": "d4",
          "title": "Explain why your evidence matters",
          "minutes": 10,
          "mode": "Work in pairs",
          "intro": "A number on its own does not explain an argument. Tell your partner how your evidence helps answer the essay question.",
          "steps": [
            "Choose two notes from your evidence table. Use a different note in each speaking round.",
            "Use 4 minutes per round. Partner A explains one note. Partner B reads the question on the card. A improves the explanation. Click Swap speakers, then B explains the second note.",
            "Use the last 2 minutes to write both explanations. Keep words such as “may” when the evidence has limits."
          ],
          "fields": [
            {
              "label": "Connection 1: evidence + explanation",
              "placeholder": "Evidence… This may matter because…",
              "rows": 3
            },
            {
              "label": "Connection 2: evidence + explanation",
              "placeholder": "Evidence… This supports/limits… because…",
              "rows": 3
            }
          ],
          "visual": "language",
          "support": "___ contributes to ___ because ___. Reducing ___ may ___, which matters because ___. This suggests that ___, although ___.",
          "feedback": "Check that every link is supported. Avoid turning “could feed” into “will feed”, or a US figure into a global one. A good connection explains the mechanism between waste reduction and food security rather than just repeating a number.",
          "deliverable": "Two sentences linking evidence to your reasons."
        },
        {
          "id": "d5",
          "title": "Choose your answer and plan the essay",
          "minutes": 20,
          "mode": "Discuss together → write your own plan",
          "intro": "First discuss possible answers. Then make your own plan in the boxes below.",
          "steps": [
            "For 4 minutes, discuss how important food-waste action is. Choose two different reasons for your answer.",
            "For 11 minutes, fill in your own plan. Your thesis is your main answer. For each body paragraph, add a reason, evidence with a source, and an explanation.",
            "For 5 minutes, exchange plans. Ask: Are the two reasons different? Does the evidence support them? Do the explanations answer “How critical”?",
            "Improve your plan after the discussion. Use notes and short phrases. Do not write the full essay yet."
          ],
          "fields": [],
          "kind": "plan",
          "question": true,
          "support": "Possible position frames: Addressing food waste is critical because ___. / It is an important part of the strategy, although ___. / Its importance depends on ___.",
          "feedback": "Your plan needs a position, two supporting arguments, selected evidence and explanations. Environmental consequences and better resource use are possible organising ideas, but you can justify another evidence-based structure. Do not copy a model conclusion or treat the scaffold as an official marking rubric.",
          "deliverable": "Your own essay plan with two different reasons and supporting evidence."
        },
        {
          "id": "d6",
          "title": "See what you learned. Get ready for Monday.",
          "minutes": 5,
          "mode": "Work alone",
          "intro": "Check your plan, name one change in your thinking, and save your work.",
          "steps": [
            "Use 1 minute to check the list. Tick only the things your plan already has.",
            "Use 2 minutes to compare your first note with later work in the Before / now panel. Write one change or something you still need help with.",
            "Use 1 minute to write a question for Monday. Use the last minute to download and open your notes file. Bring it with your handwritten notes and plan.",
            "Before Monday, keep improving the plan. Do not write the essay yet or ask AI to write it."
          ],
          "fields": [
            {
              "label": "My question for Monday",
              "placeholder": "I would like help with… My question is…",
              "rows": 3
            },
            {
              "label": "Before / now / next: one change and one next action",
              "placeholder": "At first I wrote/thought… Now I can show… My next action is…",
              "rows": 4
            }
          ],
          "kind": "checklist",
          "checks": [
            "I have a clear position that answers “How critical”.",
            "I have two distinct arguments.",
            "I have selected notes from the two readings and the listening.",
            "My notes identify sources and preserve the scope of the evidence.",
            "I can explain how my evidence supports my arguments.",
            "I have revised my plan after discussion."
          ],
          "feedback": "Unchecked items tell you what to revisit, not a grade. Focus on the weakest link in your plan. Keep the original question and 450–600-word target for Monday. Use Download notes to keep a portable copy.",
          "deliverable": "A saved plan, one example of learning, and a question for Monday."
        }
      ]
    }
  ],
  "extras": [
    {
      "id": "x1",
      "title": "Retrieve six useful words",
      "minutes": 12,
      "mode": "Optional · solo",
      "intro": "Close the glossary. Explain these words without copying: evidence, assumption, bias, redistribution, emissions, critical.",
      "steps": [
        "Write brief definitions from memory.",
        "Use two words in sentences connected to the essay topic.",
        "Open the glossary and repair your definitions."
      ],
      "fields": [
        {
          "label": "Definitions from memory",
          "placeholder": "Write your ideas here…",
          "rows": 5
        },
        {
          "label": "Two original sentences",
          "placeholder": "Write your ideas here…",
          "rows": 3
        }
      ],
      "feedback": "Check precision: evidence supports a claim; an assumption is an unstated premise; bias favours a perspective; redistribution changes who receives resources; emissions are releases such as gases; critical here means very important. A definition is stronger if you can use the word accurately."
    },
    {
      "id": "x2",
      "title": "Watch with a comparison question",
      "minutes": 15,
      "mode": "Optional · listening",
      "intro": "The original public video is supplementary here. The course transcript is adapted, so the versions may differ.",
      "steps": [
        "Predict: which cause of waste might be hardest to change?",
        "Watch the food-waste section from 00:00:09 to 00:09:05. Note one cause, one consequence and one proposed action. Open the video script to check the timestamps.",
        "Compare one detail with the course transcript. Distinguish a source difference from a note-taking mistake."
      ],
      "fields": [
        {
          "label": "Cause, consequence and action",
          "placeholder": "Write your ideas here…",
          "rows": 3
        },
        {
          "label": "One comparison with the course version",
          "placeholder": "Write your ideas here…",
          "rows": 3
        }
      ],
      "kind": "video",
      "feedback": "Check your notes against what you actually heard. Label them “original video” when they differ from the adapted course material. Use the protected course sources for the planned class essay.",
      "sources": [
        "video-script",
        "listening"
      ]
    },
    {
      "id": "x3",
      "title": "Qualify an overclaim",
      "minutes": 10,
      "mode": "Optional · writing",
      "intro": "Practice case: “Our town has surplus food. Giving it away will permanently remove hunger in every country.”",
      "steps": [
        "Identify the claim that is too broad.",
        "Rewrite it using “can”, “may” or a condition, without empty hedging.",
        "Explain one practical limit that needs evidence."
      ],
      "fields": [
        {
          "label": "My revised claim and explanation",
          "placeholder": "Write your ideas here…",
          "rows": 3
        }
      ],
      "feedback": "A defensible version might say donations can improve access where edible surplus is collected safely and reaches people who need it. Distribution, reliable supply and access matter. This is sentence practice, not the full essay."
    }
  ],
  "glossary": [
    [
      "relay",
      "A team activity where people take turns. Here, each person takes a speaking job, then the jobs change.",
      "Take turns; then change jobs."
    ],
    [
      "argument",
      "Your answer or position, supported by reasons and evidence. Here it does not mean a fight.",
      "My argument is that… because…"
    ],
    [
      "claim",
      "A statement that someone says is true. It needs checking.",
      "The writer claims that…"
    ],
    [
      "evidence",
      "Information that helps support or check an idea, such as a result from a study.",
      "What evidence supports this idea?"
    ],
    [
      "source",
      "The text, video, study or person that information comes from.",
      "Record the source and paragraph."
    ],
    [
      "assumption",
      "An idea that an argument depends on but has not shown to be true.",
      "This assumes that…"
    ],
    [
      "bias",
      "A tendency to favour one point of view over others.",
      "Whose point of view gets more attention?"
    ],
    [
      "scope",
      "The people, places, years or topics that information covers.",
      "Does this describe one city or the whole world?"
    ],
    [
      "traceable",
      "You can follow the details back to information you can check. This does not mean the claim is true.",
      "Can I find the method or original study?"
    ],
    [
      "paraphrase",
      "Explain the same idea in your own words. Keep its meaning and name the source.",
      "Read, look away, write, then check."
    ],
    [
      "thesis",
      "The main answer or position in your essay.",
      "My main answer is…"
    ],
    [
      "position",
      "What you think about the question, supported by reasons.",
      "My position is that…"
    ],
    [
      "provisional",
      "A first idea that you may change later.",
      "This is my first answer; I will check it."
    ],
    [
      "verify",
      "Check whether information is accurate.",
      "Check the number in the original source."
    ],
    [
      "peer",
      "Another student in your class or group.",
      "Ask another student for feedback."
    ],
    [
      "feedback",
      "Comments about your work that can help you improve it.",
      "One useful thing you did was…"
    ],
    [
      "self-regulation",
      "Planning your learning, checking how it is going, and changing what you do when needed.",
      "Plan → check → change your action."
    ],
    [
      "critical",
      "In the essay question: very important. In critical reading: examining ideas carefully.",
      "How important is this action?"
    ],
    [
      "food insecurity",
      "Not having reliable access to enough safe and nutritious food.",
      "Food may exist, but people may not be able to get it."
    ],
    [
      "redistribution",
      "Moving food or other resources from people who have extra to people who need them.",
      "A food bank redistributes donated food."
    ],
    [
      "emissions",
      "Gases or other substances released into the air or environment.",
      "Greenhouse gas emissions."
    ],
    [
      "surplus",
      "More than is needed.",
      "Surplus food = extra food."
    ],
    [
      "consumption",
      "Using something; here, eating or using food.",
      "Food produced for consumption."
    ],
    [
      "mitigate",
      "Make a problem or its effects less serious.",
      "Mitigate an impact = reduce its effect."
    ],
    [
      "landfill",
      "A place where waste is buried in the ground.",
      "Food sent to landfill."
    ],
    [
      "methane",
      "A gas that traps heat in the atmosphere. It can be released when food breaks down without oxygen.",
      "Methane is a greenhouse gas."
    ],
    [
      "decomposes",
      "Breaks down or rots over time.",
      "Food decomposes."
    ],
    [
      "produce",
      "As a noun here: fruit and vegetables grown for food.",
      "Fresh produce."
    ],
    [
      "edible",
      "Safe and suitable to eat.",
      "Edible food."
    ],
    [
      "abundance",
      "A large amount of something.",
      "An abundance of food."
    ],
    [
      "incentive",
      "Something that encourages a person or organisation to act.",
      "A financial incentive."
    ],
    [
      "perspective",
      "A way of seeing or thinking about something.",
      "A farmer’s perspective."
    ],
    [
      "relevance",
      "How closely information connects to your question.",
      "Explain why this evidence is relevant."
    ],
    [
      "limitation",
      "Something information cannot show, or something a method cannot do well.",
      "A study of one place has limits."
    ],
    [
      "scenario",
      "An imaginary situation used for practice.",
      "Read the practice situation."
    ],
    [
      "acknowledge",
      "Say where help or information came from.",
      "Report AI help when your task rules require it."
    ],
    [
      "theme",
      "A main idea used to group related information.",
      "Group notes with the same theme."
    ],
    [
      "qualify",
      "Make a statement more careful by adding a limit or condition.",
      "Say where or when the statement applies."
    ],
    [
      "causal",
      "About how one thing causes or contributes to another.",
      "Explain the cause-and-effect link."
    ],
    [
      "judgement",
      "An opinion or decision based on what you know.",
      "Make a judgement about importance."
    ],
    [
      "supply chain",
      "The steps and organisations that move food from farms to the people who use it.",
      "Farm → storage → transport → shop → home."
    ],
    [
      "harvesting",
      "Collecting a crop when it is ready.",
      "Harvesting fruit from trees."
    ],
    [
      "post-harvest",
      "After a crop has been collected.",
      "Post-harvest storage."
    ],
    [
      "malnutrition",
      "Poor nutrition because the food someone gets does not meet their body’s needs.",
      "Enough calories do not always mean good nutrition."
    ],
    [
      "undernourishment",
      "Not getting enough food energy over time.",
      "A lack of enough food to meet energy needs."
    ],
    [
      "profitability",
      "How much money remains after the costs of running a business.",
      "Lower costs can improve profitability."
    ],
    [
      "livelihoods",
      "The ways people earn money or get what they need to live.",
      "Farming supports many livelihoods."
    ],
    [
      "sustainable",
      "Able to continue over time without using up resources or causing lasting harm.",
      "A sustainable way to produce food."
    ],
    [
      "sustainability",
      "The ability to continue over time while protecting resources and future needs.",
      "Think about long-term effects."
    ],
    [
      "conserves",
      "Protects something by avoiding unnecessary use or loss.",
      "Conserves water = saves water."
    ],
    [
      "households",
      "People who live together in one home, or one person living alone.",
      "The study counts homes, not individual people."
    ],
    [
      "nutrition",
      "How food supplies what the body needs to live and stay healthy.",
      "Nutrition involves the amount and type of food."
    ],
    [
      "nutritious",
      "Providing useful nutrients for the body.",
      "Nutritious food."
    ],
    [
      "nutritional deficiencies",
      "Not having enough of one or more nutrients the body needs.",
      "A shortage of a nutrient."
    ],
    [
      "chronic diseases",
      "Illnesses or health conditions that last a long time.",
      "Chronic means lasting over time."
    ],
    [
      "economic stability",
      "A situation where jobs, income and prices are reasonably steady.",
      "Large economic changes can affect access to food."
    ],
    [
      "retail",
      "Selling goods directly to customers.",
      "Supermarkets are part of food retail."
    ],
    [
      "distributed",
      "Moved or delivered to different places or people.",
      "Food is distributed to shops."
    ],
    [
      "denominator",
      "The total that a fraction or percentage is based on.",
      "For 20% of households, the total is all households counted."
    ],
    [
      "AI chatbot",
      "A computer program you can type questions or instructions into. It can produce answers or writing, but its answers can be wrong.",
      "Use your own thinking and check the information."
    ]
  ]
};
