window.DEC15_SOURCES = [
  {
    "id": "listening",
    "title": "Food waste causes climate change",
    "cite": "Our Changing Climate (2020)",
    "kind": "Core listening transcript",
    "reference": "Adapted from: Our Changing Climate. (2020, March 28). Food waste causes climate change: Here’s how we stop it [Video]. YouTube. https://www.youtube.com/watch?v=1MpfEeSem_4",
    "paragraphs": [
      "A. Curries. Burgers. Sushi. Pizzas. Tortillas. As a species, food is central not only to our survival, but also to our cultures. We love food. But as much as we love food, we also love to throw it away. The UN Food and Agriculture Organization estimates that globally almost one-third of food produced for consumption never gets eaten. And in the U.S., that number is even higher. 40% of the U.S.’s available food supply gets wasted every year. As a report from the NRDC notes, that’s like buying five bags of groceries at the store and then just leaving two of them in the parking lot every time you shop. So today, we’re going to look at food waste with three questions. Why is excessive food waste happening? What are its environmental consequences? And how can we fix it?",
      "B. If all the food currently getting thrown in the landfill every year was instead diverted into meals for those in need, we’d be able to feed as many as 1.8 billion people. On top of that, food waste has been estimated to be responsible for roughly 8% of global emissions. If it was a country, it would rank third under China and the United States for yearly greenhouse gas emissions. Its large emissions footprint not only comes from all the energy needed to ship, process, and produce the food that ends up in the trash, but also from the potent methane fumes that food emits as it decomposes in landfills. So, food waste is one of the many issues at the crossroads of climate action and social justice.",
      "C. But food doesn’t just sprout out of the ground and then magically end up in the trash. There’s a long chain of business and consumer interactions that at any point might turn perfectly edible food into waste. Simply put, food transforms into trash in two general areas as it travels from farm to plate, before the point of sale and after the point of sale. If we look at this chart, the majority of the food waste generated in the United States comes after the point of sale. But let’s look at the food loss before that, on farms and in grocery stores, in order to understand how this all starts.",
      "D. Before I transitioned to making YouTube videos full-time, I worked in a number of food-related positions where I saw firsthand how the drive for perfect, abundant produce perpetuated an unnecessary trend of food waste. As a farmhand at a number of different farms, when I saw insect bites on arugula leaves or blemishes on peppers and tomatoes, I knew they were destined to rot. All that time, effort, and fuel wasted because the farm manager knew that better-looking produce will always sell over imperfect ones. These cosmetically-challenged products, as they’ve come to be known, can often end up left on the ground by harvesters or even make their way to landfills, adding to piles of food that decomposes and generates harmful emissions.",
      "E. But the aesthetics of produce are just one part of the picture. Market prices for food can also affect whether crops make it through the harvest. According to one recent study that analysed on-farm food loss in California, 33.7% of produce remains unharvested every year. That’s the equivalent of growing 300 acres of cantaloupe and leaving 100 acres of it to decay in the fields. Which, according to an article from Civil Eats, is exactly what happened to sixth-generation farmer Cannon Michael. Michael couldn’t justify paying workers to pick the cantaloupe because the cost of labour, packing, and shipping would have been more than the price he could get for the fruit.",
      "F. And even if the food does make it off farms, it still has to navigate the gauntlet of grocery store aisles. One of the best ways to sell food is through the illusion of abundance. People shop visually, and to most, that last apple on the shelf was left there because there was something wrong with it, not because it just happened to be the last one. In order to appear abundant, grocery stores often overbuy food to trick people into purchasing items. As a result, produce inevitably goes to waste as it sits out all day like glorified window dressing. Farmer Delaney Zayach explains this dilemma in the documentary Just Eat It. So, at the grocery store and farmers markets, vendors face an uphill battle against the old saying, pile it high and watch it fly. They need to produce an excess of food to sell their goods, but that excess can at times lead to more waste.",
      "G. After the point of sale, the plague of food waste continues. Indeed, household, restaurant, and food service waste accounts for 69% of the United States’ annual food waste. As a consumer and lover of food, I’ve tried hard to minimize my waste, but it can be easy to cook or buy excess that ends up in the compost or trash. For a family of four, household food waste costs $1,800 annually, and with the average plate size expanding by 36% since 1960 and with refrigerators growing 30% in volume since 1972, it’s tempting to buy more food just to fill up the space. Overbuying, and the inevitable cleaning out the refrigerator activity that comes with it, can also be attributed to buy-one-get-one promotions or purchasing in bulk. Our appliances, supermarkets, and even our plates are all nudging us to buy more.",
      "H. In addition to overbuying, in the United States, there is also a severe lack of clarity when it comes to dealing with expiration dates and spoiled goods. There are no federal laws regulating sell-by or expiration dates. As a result, labels can mean basically anything depending on where you buy your food. In Missoula, Montana, for example, milk’s sell-by date is set at 12 days after pasteurisation, even though the standard is 21–24 days. That’s because, in most cases, these dates are set by the milk producer and not a regulatory service. As one grocery vendor in Missoula laments, the 12-day sell-by date tells the consumer nothing. It’s just an arbitrary number somebody came up with with no scientific backing whatsoever. This lack of clear information regarding when a product actually goes bad means that households throw out perfectly edible food well before it expires.",
      "I. In short, there are marketing, labelling, cultural, and psychological forces all coming to play in order to make food waste a large problem in the United States. "
    ]
  },
  {
    "id": "reading1",
    "title": "Exploring the impact of food waste",
    "cite": "Tchonkouang et al. (2023)",
    "kind": "Core reading 1",
    "reference": "Adapted from: Tchonkouang R. D., Onyeaka, H., & Miri, T. (2023). From waste to plate: Exploring the impact of food waste valorisation on achieving zero hunger. Sustainability, 15(13), Article 10571. https://doi.org/10.3390/su151310571 ",
    "paragraphs": [
      "A. Hunger and food waste are long-standing interconnected challenges that have plagued humankind for centuries. Food waste comes from various sources, including consumption habits and problems within the food supply chain. Given the growing concerns regarding food insecurity, malnutrition, and hunger, there is an urgent need to recover and repurpose as much food waste as possible. ",
      "B. Food waste and its impact on global food security has gained significant attention. The terms “food loss” and “food waste” might seem similar, but they refer to different issues. Food loss happens when food loses quality and quantity during production, harvesting, and distribution, often because it doesn’t look perfect (Castagna, 2021). This makes the food unsellable even though it's still safe to eat (Santeramo, 2021). Food waste, on the other hand, is when people intentionally throw away food that's still good to eat. This can happen for various reasons like buying too much, not eating it in time, or misunderstanding labels on food (Davenport et al., 2019).",
      "C. Food waste and losses happen at every stage of the food production chain. The most significant losses occur during the early stages of production and post-harvest in less developed countries, often due to poor practices and limited technology (Block et al., 2016). In more developed countries, most food waste happens at the consumer level, mainly in homes (Tan et al., 2022). Consumer behaviour, values, and attitudes significantly influence waste.  Food waste often happens during preparation and cooking. Misunderstanding expiration dates also leads to a lot of waste (Pandey, 2021).",
      "D. In Australia, a significant amount of food is wasted every year. Reynolds et al. (2015) stated that reducing this waste by one third could save up to 1.8 trillion calories which is enough to feed 921,000 people for one year. This highlights the huge potential of saving food to address hunger.",
      "E. According to the UNEP Food Waste Index Report (2021), over 931 million tonnes of food are wasted each year globally. This is concerning, especially as the world aims to meet the Sustainable Development Goals by 2030, which includes reducing food wastage by half at retail and consumer levels and decreasing losses across the supply and production chains. Meanwhile, hunger is rising, with millions suffering from undernourishment and malnutrition (Behera et al. 2019). The United Nations (2023) reported that in 2020, 3 billion people couldn't afford a healthy diet, and up to 811 million were facing hunger. Also, as the global population grows, the demand for food continues to rise.",
      "F. In addition to causing food insecurity and hunger, food loss and waste are also economic and environmental problems. When food quality drops to the point where it must be sold at lower prices or thrown away, it reduces profitability and threatens the livelihoods of farmers and producers. Food production uses many resources; thus, food waste also results in the wastage of water, land, energy, and other natural resources (Rezaei & Liu, 2017).",
      "G. Addressing food loss and waste is a sustainable strategy to achieve zero hunger (SDG 2). This effort can also help address other Sustainable Development Goals, showing that reducing food loss can help solve other related issues. Therefore, reducing food waste while feeding a growing population remains a continuous global challenge that is crucial for creating a sustainable future where everyone has enough food.",
      "H. Resolving the issues of hunger and food waste are critical for achieving global food security and sustainability. Reducing food waste not only reduces hunger but also conserves valuable resources and reduces environmental impact. By focusing on both preventing food loss and ensuring efficient food usage, we can take significant steps towards the United Nations Sustainable Development Goals, particularly the goal of zero hunger."
    ],
    "figure": "assets/reading1-figure.png",
    "figureAlt": "Bar chart. Estimated household food waste, million tonnes per year: Eastern Asia 106.36; North America 22.3; North Africa 22.11; Eastern Europe 15.16; Western Europe 14.24; Southern Europe 11.97; Northern Europe 7.56; Central Asia 6.35.",
    "figureCaption": "Estimated household food waste (in million tonnes per year) in selected regions. ",
    "figureCredit": "Note: Data obtained from the database of the UNEP Food Waste Index Report 2021"
  },
  {
    "id": "reading2",
    "title": "The folly of food waste amidst food insecurity",
    "cite": "Royer (2024)",
    "kind": "Core reading 2",
    "reference": "Adapted from: Royer, M. (2024). The folly of food waste amidst food insecurity in the United States: A literature review. Challenges, 15(2), Article 21. https://doi.org/10.3390/challe15020021 ",
    "paragraphs": [
      "A. Food insecurity is a major problem where people don't always have enough healthy food to eat. Although the U.S. is the wealthiest country in the world, more than one out of every ten households face food insecurity every year (Coleman-Jensen et al., 2024). Addressing this problem could greatly improve health, the economy, and social conditions in the U.S.",
      "B. The U.S. Government started studying food security in the 1990s, beginning with the National Nutrition Monitoring and Related Research Act of 1990 (Bickel & Hamilton, 1997). This law was designed to improve nutrition monitoring, set up related programs, and provide dietary guidelines to the public. The government also created specific tools to accurately measure how widespread food insecurity is across the country.",
      "C. Over the years, the rate of food insecurity has varied. It was at its lowest in 1999, affecting 9.7% of households, and reached its highest in 2011, affecting 14.9% of households (Andrews et al. 2000; Coleman-Jensen et al., 2024). The financial crisis of 2007-2008 caused a sharp increase in food insecurity, showing how closely food security is linked to economic stability (Nord et al., 2008). As of 2022, about 12.8% of U.S. households, or 17 million households, were struggling with food insecurity (Rabbit et al., 2023). Within this group, 6.8 million faced very low food security, which affected both the quality and amount of food they could eat.",
      "D. The effects of food insecurity go beyond just being hungry. It can seriously harm both physical and mental health. People dealing with food insecurity often have nutritional deficiencies and are more likely to suffer from chronic diseases like diabetes and heart problems (Sun et al., 2020; Strings et al., 2016), as well as mental health issues such as stress and depression (Martin et al., 2016). The impact varies among different groups of people, with noticeable differences based on age, gender, income, and race. Middle-aged adults, women, and low-income families, especially those from Black, Indigenous, and People of Color communities, are especially affected by food insecurity (Walker et al., 2021; Loopstra & Tarasuk 2013).",
      "E. Despite the high levels of food insecurity, there is also a big problem with food waste. Food waste refers to edible food that is thrown away at the retail or consumer stages. In the U.S., about 30 percent (66.5 million tons) of edible food is wasted each year after it leaves the farm (Buzby et at., 2014). By improving food rescue and redistribution programs, we could reduce food insecurity and also promote public health by making sure nutritious food reaches those who need it instead of being thrown away.",
      "F. Solving the problem of food waste would not only help reduce food insecurity but would also significantly lower greenhouse gas emissions, which harm our environment and contribute to climate change. Recent data shows that 15 percent of city waste in the U.S. is food waste (EPA, 2017). This waste produces methane, a powerful greenhouse gas. It is estimated that each person in the U.S. wastes enough food each year to produce 315 pounds of greenhouse gases (King & Hough, 2010). Therefore, reducing food waste has health, social, and environmental benefits.",
      "G. The pressing issue of Food insecurity is in the United States is worsened by high levels of food waste. Improving food security means not only improving economic conditions and public health policies but also addressing inefficiencies in how food is produced, distributed and consumed. By reducing food waste, we can help ensure everyone has access to the food they need and also support broader community and environmental health goals. This approach benefits not just those directly affected by food insecurity but the wider community and environment as well."
    ]
  }
];
