/* DEC15 · Week 3 — protected course texts (copied exactly from the Teacher's Book; do not edit).
   Headings inside a text start with "## ". */
window.DEC15_SOURCES = [
  {
    "id": "nicastro",
    "short": "Reading · Nicastro & Carillo",
    "title": "Food loss and waste prevention strategies",
    "cite": "Nicastro & Carillo (2021)",
    "kind": "Core reading",
    "reference": "Adapted from: Nicastro, R., & Carillo, P. (2021). Food loss and waste prevention strategies from farm to fork. Sustainability, 13(10), Article 5443. https://doi.org/10.3390/su13105443",
    "citeAs": "Cite as Nicastro and Carillo (2021) or (Nicastro & Carillo, 2021).",
    "paragraphs": [
      "A. Globally, about one-third of the food produced for human consumption is lost or wasted each year (FAO, 2021). This not only represents a significant loss of natural resources but also negatively impacts food security. Food loss typically occurs between production and distribution, especially in low-income countries, while food waste is more common at the consumer level in developed countries, particularly in retail and food service sectors (Parfitt, et al., 2011). Preventing food loss and waste is therefore a potential strategy to improve food security while reducing environmental impact and providing economic benefits to the different actors in the food supply chain.",
      "## Preventing Food Loss and Waste at Harvest and Production",
      "B. In the European Union, 19% of food waste comes from processing food (FUSIONS, 2019). To reduce this, using better processing methods, offering different package sizes, and using new packaging ideas can help. For example, Tesco in the UK is trying out new packaging that includes a strip that slows down fruit ripening, which could keep fruits fresh longer without costing shoppers more. Also, using smaller boxes for bananas has helped reduce waste and CO2 emissions because the bigger boxes were too large for some stores (WRAP, 2019).",
      "C. Improving transportation methods and reducing the distance food travels can also prevent loss. However, it's important to balance this with environmental considerations. As Wakeland (2012) points out more frequent, smaller deliveries might increase the carbon footprint. Ensuring clear communication within the food supply chain is also crucial to avoid imbalances between supply and demand, which can lead to food loss (Beretta, 2013)",
      "## Preventing Food Loss and Waste at Retail",
      "D. In the European Union, about 5 million tonnes of food waste happen in the retail sector each year (FUSIONS, 2019). In developing countries, poor market conditions like not enough space and bad hygiene lead to a lot of food waste. Simple fixes like adding roofs to protect food can make a big difference (FAO, 2021). In developed countries, analysis carried out by Gunders (2012) showed that selling items close to their expiry date at lower prices has helped keep customers happy without reducing sales. Retailers like Sainsbury’s and Tesco have introduced \"Buy one, get one later\" campaigns, which allows customers to receive a second identical product later for free. This helps to reduce the impulse of over-purchasing from typical “Buy one, get one free” campaigns.",
      "## Preventing Food Loss and Waste at Consumption",
      "E. In Europe, households are responsible for over 50% of all food waste, which is about 47 million tonnes each year (FUSIONS, 2019). This often happens because people don't realize how many resources are needed to make and sell food, and because stores encourage buying more than needed (Flanagan et al., 2019). Campaigns like “Love Food, Hate Waste” by WRAP and “Save Food Cut Waste” in Singapore play a crucial role in educating consumers about reducing waste through practical tips and raising awareness about the environmental and social impacts of food waste (UNEP 2021).",
      "## Redistribution of Food",
      "F. According to the food waste hierarchy, the best approach is to prevent food waste. This means we should try to avoid making too much food in the first place. When the production of excess food is unavoidable, it is important to focus on giving this food to people who need it. This not only helps fight hunger but also stops the food from being used in less useful ways, like for industrial purposes or being thrown away in landfills (EU Platform on Food Losses & Food Waste, 2019).",
      "G. Many organizations worldwide collect food from companies, food services, or retailers that would otherwise go to waste (BCFN 2021). They give this food to places that help people in need. For example, the “Buon Fine Coop” initiative has been working since 1990 to reduce food surpluses from Coop supermarkets by donating them to groups like the “Fondazione Banco Alimentare Onlus.” These groups then use the food to make meals or give it as ingredients to help those who are hungry. All the food given away is still good to eat but might be removed from shelves because it doesn't meet quality standards or is close to its expiry date (Caldeira et al., 2019). Therefore, when we can't prevent making too much food, it is crucial to prioritize giving it to people before using it for other purposes.",
      "## Conclusion",
      "H. Reducing food loss and waste is vital for improving food security, saving natural resources, and lessening environmental damage. From better processing and packaging at the production stage to smarter buying campaigns for consumers, many steps are being taken to tackle this global issue. Also, giving away extra food is not just about reducing waste; it's also about reducing hunger. By continuing to find new ways and apply these methods throughout the food supply chain, we can progress towards a world that is more sustainable and food-secure world."
    ],
    "figure": "assets/week3/nicastro-household.jpg",
    "figureAlt": "Diagram: measures to prevent household food waste arranged in a circle around the words Household consumption — charity, recipes to use up leftovers, making a shopping list, planning meals, overcoming the aesthetic barriers, understanding expiry dates, portions of food, and storage.",
    "figureCaption": "Measures to prevent and reduce food waste at household consumption (part a of Figure 1).",
    "figureCredit": "Source: Nicastro, R., & Carillo, P. (2021). Sustainability, 13(10), Article 5443."
  },
  {
    "id": "aboutthat",
    "short": "Listening · About That",
    "title": "Is this the future of food banks?",
    "cite": "About That (2024)",
    "kind": "Core listening transcript",
    "reference": "Adapted from: About That. (2024, June 5). Is this the future of food banks? [Video]. YouTube. https://www.youtube.com/watch?v=D6_WVj2xrJI",
    "citeAs": "Cite as About That (2024) or (About That, 2024).",
    "note": "Speakers: AC = Andrew Chang (presenter) · VT = Valerie Tarasuk · JB = John Bailey · SW = Sarah Watson · and three food bank users.",
    "paragraphs": [
      "## Section A",
      "AC: You’re at a food bank, you’re lining up and you’re tired.",
      "Food bank user 1: It’s food drive day, I’m in the line right now, I’m a little early because if you don’t come early you are here for way longer than necessary.",
      "AC: You get handed a box, you open it up because you’re going to feed your family with whatever’s inside but you didn’t choose what’s inside and maybe that rutabaga at the bottom, you don’t even know what that tastes like, never mind how to prepare one in a meal.",
      "Food bank user 2: We also got some rockfish fillets which I’ve never worked with these before but I’m going to learn, I’m going to figure something out, I always do.",
      "AC: So that’s one type of food bank but here’s another. Conceptually it’s as close to a supermarket as you’ll get. Everything’s on display, it’s open five days a week except here the food is free. You come in, you fill your cart, you leave. You come back in two weeks and you do it again. You make the choices, you never leave empty-handed, you never pay a cent. When I read about this novel approach to food banking I immediately had questions. Like can anybody just show up and take anything? How does the food bank afford this and does this business model even work?",
      "## Section B",
      "AC: Conventional food banks all suffer from the same problem, money. Money is why they never have enough space. It’s why they’re always desperate for volunteers. It’s why they focus on efficiency. They get food in bulk, they get it out the door.",
      "VT: Food banks typically are volunteer run and in many, many places especially now we’re getting reports that the demand for assistance far outstrips supply. I mean they’re just working flat out to provide people with whatever they’ve got.",
      "AC: Predetermining what everybody is going to get gives food banks total control. But there are some problems with that. One, I might already feel helpless having to rely on a food bank in the first place. Don’t tell me what to eat on top of it.",
      "Food bank user 3: They gave me four of these which all expired two and a half months ago.",
      "## Section C",
      "AC: And a second problem stems from this. If I receive something I don’t want I might not use it.",
      "JB: Sometimes in our efforts to make sure we’re giving them great product and well-rounded product we’re giving folks stuff that they just don’t want to use.",
      "AC: And when it comes to waste if I run a food bank let’s say how would I even know what’s being used and what’s being thrown out? Like my clients might tell me I don’t like rutabagas. Andrew why do you guys always give so many rutabagas? But beyond that it’s not like I’m watching people at home to see what gets used and what gets wasted. Plus, I’m busy. I can barely find enough volunteers on a regular basis to keep my doors open because the volunteer work itself can be pretty tedious. Two main volunteer jobs are the lifeblood of a hamper model food bank. You’re either the box preparer or the box distributor. Both jobs are exactly what they sound like. Person A spends hours manually filling hundreds of identical boxes with the same foods over and over again, while Person B handles the client side of things, matching boxes to names on a list and giving them out. Point is, with all the volunteer opportunities out there these roles aren’t always easy to fill.",
      "VT: It’s really challenging for the volunteers in those settings to balance the supply and demand at the same time as trying to put some quality control on.",
      "## Section D",
      "AC: So let’s discuss a different way.",
      "AC: So those renders of what a different kind of food bank might look like that I showed you at the start. Those aren’t just concept drawings. It’s a real space set to open very soon in Saskatchewan.",
      "JB: We’re excited but we’re also a little bit nervous. Like anytime you’re trying to do something new and it’s a big change. There’s lots of planning and lots of coordination goes into it. But we’re really excited about the potential impact we can make.",
      "AC: The Regina Food Bank bought the building. It’s going to be a national first on this scale functioning very much like a grocery store.",
      "JB: You can pick ground beef or you can pick chicken. You can pick carrots or you can pick potatoes. You can pick lentils or you can pick oats.",
      "AC: Now you still need to answer some basic questions about your income, your need, the size of your family and shopping is by appointment. Then once you’re in you have an allotment of how many things you’re allowed to take. They figure every family leaves with about $200 in goods twice a month. Now that’s not necessarily any more or less than usual. It’s just distributed differently. And recreating this grocery store experience is very intentional. It’s about giving autonomy. Giving someone the dignity of being able to choose their own meals. And the financial side of that. Nobody’s forced to take something they don’t want or need.",
      "JB: That’s a real challenge for them because it creates a burden of what are they going to do with it? And also that burden of going like well I’m using that. I’m taking up this resource and somebody else can’t. So we want to eliminate that and give that empowerment.",
      "## Section E",
      "AC: And here’s the best part. When I put all of those rutabagas on my store shelves and nobody takes them, I can immediately see that I need to stop buying them. I can measure what’s popular and what’s getting left behind. Clients might be tempted to try new foods that they’re actually interested in. They can more easily shop around allergy concerns or dietary needs. And all those volunteers you had working the back room packing boxes, now they’re out front helping clients with their shopping, helping with meal planning or just helping.",
      "JB: It seems like something that’s quite appealing to folks because it allows them to really donate their time to something that where they can see the, the impact and have that interaction with the folks we serve.",
      "AC: Sounds great, right? Well let’s stay calm because it’s not easy developing a system like this that actually works. Inventory management is much more dynamic. Volunteer demands are different. The basic execution of what a food bank does is very different. And we know this because we spoke with someone who’s been operating this model for about nine years now.",
      "## Section F",
      "SW: My name is Sarah Watson and I am the Director of Community Engagement at North York Harvest Food Bank.",
      "AC: I reached out to Sarah because I found this article from 2015 about how North York Harvest Food Bank was increasingly going in favour of a client choice model. Being in control of your food feels great, they wrote.",
      "SW: What was really clear to us was that choice was a key piece of what our participants were looking for.",
      "AC: The challenge was that switching models didn’t change how much food was available. So, they had to figure out a system that worked for them.",
      "SW: So we have all the food sort of set up in the different sections and then depending on how many people are in a household, they can choose a certain number of items from that section. There’ll be a vegetable section and they’ll pick the vegetables that best meet their family’s needs. There’ll be rice and grains and pasta.",
      "AC: So there are these built-in limits on how people can shop. The trick was being able to give clients meaningful choices.",
      "JB: We just feel like this is a big step forward. To the best of our knowledge, this is going to be the largest in Canada, day one, and we only hope to ramp up from there.",
      "## Section G",
      "AC: So, is the choice model the future of food banking? Well, you know, one thing we haven’t talked about is whether this is the most efficient way to get people the food they need. You know, with the old system, you just gave people a box and they go. Now, they’re scheduling appointments, you’re giving people time to shop. You know, will food banks be able to keep up with the high demand?",
      "VT: I cycled by a food bank in my neighbourhood on Saturday. The lineup was maybe three blocks long. And in those circumstances, nobody can afford to bring people in one at a time and walk them around the room and say, you know, choose three things from over there. What would you like over here?",
      "AC: To do this on a large scale, as I mentioned, you also need a lot of space. The Regina Food Bank secured millions of dollars in donations to pay for their new operation. But the reward for giving clients more choice, according to those who’ve made the switch, incalculable. The Regina Food Bank is set to open its choice-driven community hub sometime this summer."
    ]
  },
  {
    "id": "berti",
    "short": "Reading · Berti et al.",
    "title": "The transformative potential of food banks",
    "cite": "Berti et al. (2021)",
    "kind": "Core reading · mediation",
    "reference": "Adapted from: Berti, G., Giordano, C., & Mininni, M. (2021). Assessing the transformative potential of food banks: The case study of Magazzini Sociali (Italy). Agriculture, 11(3), Article 249. https://doi.org/10.3390/agriculture11030249",
    "citeAs": "Cite as Berti et al. (2021) or (Berti et al., 2021).",
    "paragraphs": [
      "A. Food insecurity refers to when people and families do not consistently have enough healthy food (Dowler & O’Connor, 2012). This is a significant problem in wealthy countries, where more people are finding it hard to eat well every day (Long et al., 2020). At the same time, in the European Union (EU), about 88 million tonnes of food are thrown away each year, costing around 143 billion euros (Stenmarck et al., 2020). This situation, where there is both food insecurity and food waste, is known as the “food paradox” (Galli et al., 2019; Campiglio & Rovati, 2009). It demonstrates a worrying contradiction in wealthy societies and is considered highly unethical today.",
      "B. Redistributing excess food to those who need it is often presented as a solution to the food paradox (Caplan 2016). Central to these efforts are “food banks” which generally are community-organisations led by non-profit organizations based on volunteering. Food banks collect extra food from a variety of donors, including farmers, supermarkets, restaurants and private individuals (Santini & Cavicchi, 2014). The collected food is then stored and redistributed to people in need, avoiding any food waste or misuse. Food banks are therefore presented as a win–win solution to tackle the food paradox.",
      "C. In Italy, the community-based food bank Magazzini Sociali, has been redistributing donated food since 2015. This organisation operates in a region of the country with high rates of unemployment and poverty. It emerged as a way to support local families by collecting unused food and to distributing it to those in need. As of June 2020, 39 tons of food had been collected, corresponding to 5800 donations and 4300 deliveries to families. The most frequently donated products are other meals, bread, milk, and juices. Cooked food is collected and donated as well if it has not been handled and served. The volunteers portion the food into single trays, store it in insulated trays, and transport it. If the food isn't donated the same day, they freeze it immediately. The food collection area is limited to within 30 minutes of the food hub to ensure freshness.",
      "D. Although Magazzini Sociali has undoubtedly been successful in supporting the local community, food banks remain controversial. McMichael (2009) points out that food waste and food insecurity are the result of structural problems in the global food system. Large agricultural companies that prioritise profit over human wellbeing create unnecessary waste while making access to healthy, affordable food difficult for disadvantaged groups. While food banks can provide some immediate help to people in need, they cannot solve the underlying inequalities in the food production system that cause and sustain food insecurity. At best, food banks can only offer a band-aid solution to a much larger problem.",
      "E. Despite such criticism, food banks can still play an important role in improving the food system by working in partnership with governments. Food banks, such as Magazzini Sociali, have demonstrated that they are able to develop efficient and transparent food distribution programs. They therefore have expertise that could help governments to develop programs and policies that reduce food waste and improve access to nutritious food for those in need. In addition, financial support from the government could also help food banks to ramp up their operations so that they are able to support a larger number of people than is possible through charity alone. At present, the growth of food banks is limited by their reliance on volunteers and donations. Greater collaboration with governments could therefore increase the impact of food banks on the food system.",
      "F. In conclusion, the presence of both food insecurity and food waste in wealthy areas like the European Union presents a troubling situation where too much food exists alongside widespread hunger. Food banks such as Magazzini Sociali have done well in redistributing extra food to those who need it, but they can't solve the deeper issues causing food insecurity by themselves. Their work does however show that such organizations can be key in larger efforts to improve food systems. Working together, food banks and government agencies can use their strengths to make a bigger difference."
    ],
    "figure": "assets/week3/magazzini-donations.webp",
    "figureAlt": "Pie chart of food donations to Magazzini Sociali by type. The largest shares are other meals (15.9%), second course (12.5%), bread (12.4%), milk and juices (12.2%) and other foods (11.7%). Smaller shares include pasta (7%), biscuits (5.6%), sandwiches (4.5%), tomato sauce (3.7%), canned legumes (3.5%), main course (3%), baby food (1.4%), canned meat and fish (0.9%) and oil (0.7%).",
    "figureCaption": "Food donations as at 30 June 2020, Magazzini Sociali, Potenza (Italy).",
    "figureCredit": ""
  },
  {
    "id": "discussion-sample",
    "short": "Discussion sample",
    "title": "Research Summary Discussion — negotiation stage (sample)",
    "cite": "DEC15 sample recording",
    "kind": "Discussion transcript",
    "reference": "Sample students’ discussion recorded for DEC15 (Step 5, Part 2: negotiation). Question: Which of the consequences of the modern agricultural production system is the most serious? health problems · environmental damage · animal rights violations.",
    "note": "Listen to the recording first (your teacher plays it). Then read the transcript to check.",
    "paragraphs": [
      "Student 5 (Netherlands Focus): …this point links us to one of the other options in our question: animal rights violations.",
      "Student 1 (UK Focus): Okay, let’s move on to that consequence then. In our reading, my group learnt that the UK has some of the strictest animal welfare laws in the world.",
      "Student 4 (Kenya Focus): Oh, really?",
      "Student 1 (UK Focus): Yep. Apparently for the most serious animal welfare offenses people can be sentenced to five years in prison.",
      "Student 5 (Netherlands Focus): Wow! 5 years in jail? That’s pretty strict!",
      "Student 4 (Kenya Focus): Hmmm, but I think it’s fair because I’ve seen some terrible videos about how badly some people treat animals. I hate to think about what goes on in some of these factory farms.",
      "Student 5 (Netherlands Focus): I agree, Mark.",
      "Student 1 (UK Focus): Well, in the UK, they do aim to set high standards for the treatment of farm animals, but the challenge is to balance these standards with the pressures of high productivity.",
      "Student 5 (Netherlands Focus): That’s the other issue, right? I don’t want to see animals being harmed, but I also enjoy eating meat every day.",
      "Student 4 (Kenya Focus): I disagree! I think that if we all shifted towards a largely plant-based diet, we’d minimise animal rights violations as well as the negative impacts on the environment.",
      "Student 1 (UK Focus): Yeah, I’m seriously thinking about changing my diet to eat less meat, especially considering what we’ve been reading about.",
      "Student 5 (Netherlands Focus): That’s a good point, but again this solution may be something we should be focusing on next week, not today.",
      "Student 1 (UK Focus): Okay, well let’s get back to the effects. Do you have any other thoughts about the ethical consequences of the modern agricultural production system?",
      "Student 4 (Kenya Focus): Well, animal welfare is a growing concern in Kenya as well. Traditional farming practices generally uphold decent welfare standards, but there is a shift towards more intensive farming. This raises ethical concerns, particularly regarding the confinement and treatment of livestock.",
      "Student 5 (Netherlands Focus): Hmmmm… and like you said before about the UK, the Netherlands also has high animal welfare standards, but there are still significant issues in intensive livestock sectors. While regulations are in place, the reality of industrial farming often falls short of these ideals.",
      "Student 1 (UK Focus): That’s right. It can be difficult to monitor whether the factory farms are always following the rules.",
      "Student 4 (Kenya Focus): At least we can see there are actually rules in many areas, so there’s an attempt to control it.",
      "Student 1 (UK Focus): True. And that’s why I still feel that the environmental consequences are a bigger worry than the animal welfare issues. Humans and animals all need a planet to live on!",
      "Student 5 (Netherlands Focus): Hold on, we haven’t discussed the final option of the question yet! How serious are the health problems caused by the modern agricultural production system?",
      "Student 1 (UK Focus): Well, this ties into what we were saying earlier about the overuse of chemical fertilizers. This causes problems for the environment and people’s health.",
      "Student 4 (Kenya Focus): Yes, from what we read about Kenya, using pesticides and fertilizers not only affects the health of agricultural workers but also the broader community through water contamination and food residues.",
      "Student 5 (Netherlands Focus): And in the Netherlands, the dense population and intensive farming methods increase the risk of zoonotic diseases. This is a significant public health concern.",
      "Student 1 (UK Focus): What are zoonotic diseases?",
      "Student 5 (Netherlands Focus): They’re infectious diseases that can be transmitted from animals to humans.",
      "Student 4 (Kenya Focus): Do you mean like bird flu?",
      "Student 5 (Netherlands Focus): Yeah, that’s a good example, Mark.",
      "Student 4 (Kenya Focus): Well, in addition to those types of diseases, another issue that affects human health is the use of antibiotics in livestock, which can lead to antibiotic resistance.",
      "Student 1 (UK Focus): Yeah, this issue seems to be increasing around the world.",
      "Student 4 (Kenya Focus): Hmmm… Well, all these points show that while the specifics might vary, the underlying issues are quite similar across different regions. And also, environmental damage, animal welfare, and health issues are all critical and interlinked aspects of modern agriculture.",
      "## Alternate ending",
      "Student 1 (UK Focus): Yeah, you’re right. It's clear that all these consequences are serious, but it seems that none of these issues can be viewed in isolation. Each factor affects the others.",
      "Student 4 (Kenya Focus): Yes, but the question does ask which of the consequences is the most serious. Which one do you think we should choose?",
      "Student 1 (UK Focus): They are all really significant, but I would still go with the environment.",
      "Student 4 (Kenya Focus): You’ve been pretty set on that from the start. Why are you so firm with that choice?",
      "Student 1 (UK Focus): For me, this is the most serious consequence because it affects the foundation of life on Earth, including the air we breathe, the water we drink, and the food we eat.",
      "Student 5 (Netherlands Focus): So, you’re saying that our health is affected by the environment?",
      "Student 1 (UK Focus): That’s right. And considering animal welfare, environmental sustainability is crucial not only for human health but also the survival of all species.",
      "Student 4 (Kenya Focus): I guess you’re right. Mmmm…so, should we go with that option? Environmental damage is the most serious consequence of the modern agricultural production system.",
      "Student 5 (Netherlands Focus): Yes. For me it’s much more serious than the other two options.",
      "Student 1 (UK Focus): Me too"
    ]
  }
];
